### ISSUE TITLE
Questions regarding to visualizing trained models

### ISSUE THREAD

**Issue by hangg7** [zju3dv/neuralbody#10]
Hi Sida,

Thanks for releasing the code! I am playing around with your model and have three questions about visualizing trained neural body scene:

1. **What is the difference between `render` (demo) and `perform` visualization?**

It seems to me that both visualization modes do the same thing as provided now (circular camera motion with fixed pose). These are the results of the visualization command you provided:

```python
# visualize novel views of single frame
python run.py --type visualize --cfg_file configs/xyzc_demo_313.yaml exp_name xyzc_313
```
![render](https://user-images.githubusercontent.com/10098306/112764856-41c6b880-8fbf-11eb-8dea-ec7e966544d0.gif)

```python
# visualize novel views of dynamic humans
python run.py --type visualize --cfg_file configs/xyzc_perform_313.yaml exp_name xyzc_313
```
![perform](https://user-images.githubusercontent.com/10098306/112764858-468b6c80-8fbf-11eb-809f-c9cacb0460a7.gif)

2. **How can I visualize a scene with fixed camera + temporal articulation?** 

I believe this is related to https://github.com/zju3dv/neuralbody/issues/4. My understanding is that `perform` visualization is meant to do this, but as shown in my gifs above, is not currently working.

I realize it might be the case that `perform` visualization is visualizing a circular camera motion + temporal articulation. Could you confirm?

3. **How can I repose a trained neural body scene in the current codebase? If it is possible, could you offer any pointer for getting started?**

What I meant by "reposing" is that I would like to render a video with fixed camera of, say, bending arms from A-pose to 90 degrees by changing the theta parameters.

Finally a small suggestion: 

it will definitely help and be really awesome for you to update README page with some sample results for each command and specify what are the camera motions and articulations to be visualized such that people don't have to dig into your code to find them out!

**Comment by hangg7** [comment]
All right, after hacking into the code I can answer some of the questions I have raised. This might be useful for future users as well:

1. **What is the difference between `render` (demo) and `perform` visualization?**

`render`: [spiral cameras](https://github.com/zju3dv/neuralbody/blob/master/lib/utils/render_utils.py#L61) + fixed articulation (first frame of the video).

`perform`: spiral cameras + temporal articulations as in the input video 

2. **How can I visualize a scene with fixed camera + temporal articulation?** 

I am able to do this by setting [render_views](https://github.com/zju3dv/neuralbody/blob/master/configs/xyzc_perform_313.yaml#L80) to 1 -- meaning that I will only use the first lightstage camera for rendering.

3. **How can I repose a trained neural body scene in the current codebase? If it is possible, could you offer any pointer for getting started?**
This is a bit trickier and requires some hacking. The idea is to generate interpolating vertices using new theta parameters using the [zju_smpl](https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/extract_vertices.py) as the author kindly provided. I needed to also disable [masking](https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/can_smpl_perform.py#L140) for rendering to generate correct results.

**Comment by hangg7** [comment]
As my questions having been answered, I'd like to further discuss an interesting behavior that I found in neural body. 

![reposing](https://user-images.githubusercontent.com/10098306/112773085-6fc0f280-8fe9-11eb-9f3b-9cea45b57f1b.gif)

It seems that though able to reconstruct _seen_ articulations during training (given by pseudo groundtruth theta), NB has trouble generalizing to _unseen_ articulations.

**Comment by pengsida** [comment]
Hi Hang,

Thanks for your attention and suggestions to Neural Body. I will update the document!

I also found that NB gives poor performance on unseen human poses.
I agree with you that 3D convs in duffision process cannot guarantee the feature equivariance.
Previously I repose all human parts, while not just one part. As shown in your example, it is weird that just moving one arm degrades the rendering perform on other human parts. In general, as convolution is a local operator, the diffused features at other positions should not change a lot.
Improving the network structure may help the generalization ability.
It is an interesting problem, and I have been thinking about how to improve it recently.

For dicussions on the algorithm improvement, it may be better to communicate through emails :joy:
My email is pengsida@zju.edu.cn. Any discussion is welcomed!

Best,
Sida

**Comment by pengsida** [comment]
I have updated the document. It indeed improves README a lot.
Very appreaciate your suggestions!!!
