### ISSUE TITLE
About reproduce the result of paper

### ISSUE THREAD

**Issue by daixiangzi** [zju3dv/neuralbody#101]
问下论文中的实验结果是用的params 还是new_params?

**Comment by daixiangzi** [comment]
另外我发现你论文中weight_decay明明设置为5e-5，但是你默认配置中并没有设置

**Comment by daixiangzi** [comment]
此外，我用num_frame:300,new_params，4 views复现id为313结果很差，psnr才29点左右。。。是否你遗漏了某个细节？或者是我设置有错误

**Comment by pengsida** [comment]
> 另外我发现你论文中weight_decay明明设置为5e-5，但是你默认配置中并没有设置

论文里xie写的是5e-4。
<img width="441" alt="image" src="https://user-images.githubusercontent.com/11582122/185966921-7a570bb7-337a-4932-b481-c9eeabf0ddbe.png">

配置文件里有写：https://github.com/zju3dv/neuralbody/blob/master/configs/zju_mocap_exp/latent_xyzc_313.yaml#L40

**Comment by pengsida** [comment]
> 此外，我用num_frame:300,new_params，4 views复现id为313结果很差，psnr才29点左右。。。是否你遗漏了某个细节？或者是我设置有错误

可能是训练的不够久。我重新训练没有发现这个问题。

**Comment by daixiangzi** [comment]
> > 另外我发现你论文中weight_decay明明设置为5e-5，但是你默认配置中并没有设置
> 
> 论文里xie写的是5e-4。 <img alt="image" width="441" src="https://user-images.githubusercontent.com/11582122/185966921-7a570bb7-337a-4932-b481-c9eeabf0ddbe.png">
> 
> 配置文件里有写：https://github.com/zju3dv/neuralbody/blob/master/configs/zju_mocap_exp/latent_xyzc_313.yaml#L40
我说的不是学习率哇，我说的是decays_exponentially

**Comment by daixiangzi** [comment]
> > 此外，我用num_frame:300,new_params，4 views复现id为313结果很差，psnr才29点左右。。。是否你遗漏了某个细节？或者是我设置有错误
> 
> 可能是训练的不够久。我重新训练没有发现这个问题。

默认配置文件是400epoch，你当初用了多少个epoch训练300 frames的
