### ISSUE TITLE
get_annots.py kpts2d missing

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/neuralbody#103]
Hello.
I'm trying to create my own data to use on neuralbody, but when I use get_annots, I have a problem, there is a variable in use that I dont know where it comes from.

here is the error that it shows
![image](https://user-images.githubusercontent.com/4061130/186972846-45ceac32-2cfb-463d-a233-d9fbe7ccdbcc.png)

I've made some changes on the code to better fits my files and folders, but that "kpts2d" variable was already missing

Can someone give me a help on that. thanks

Here is the full code that I'm using
![image](https://user-images.githubusercontent.com/4061130/186972764-27f1cbb9-2922-405e-a11a-7a0ed10adf6b.png)

**Comment by chingswy** [comment]
Hello, @carlosedubarreto , I will make a new interface of NeuralBody soon. You can wait for it.

**Comment by carlosedubarreto** [comment]
Thanks a  lot I'll wait then 😊
