### ISSUE TITLE
paper reproduce issues

### ISSUE THREAD

**Issue by daixiangzi** [zju3dv/neuralbody#104]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/24811131/188054179-42c74094-4726-41d9-beba-38035c68cea3.png">

**Comment by daixiangzi** [comment]
请问第一个300帧是在几个views下训练完成的，4个？另外对于测试，这个结果是取视频“Twirl",第一帧完成的吗？

**Comment by pengsida** [comment]
4个view训练的。测试在第一帧上完成。
