### ISSUE TITLE
300帧的实验是基于哪一个配置文件哇

### ISSUE THREAD

**Issue by daixiangzi** [zju3dv/neuralbody#105]
--cfg_file configs/zju_mocap_frame1_exp/latent_xyzc_313_ni1.yaml，还是 -cfg_file configs/zju_mocap_frame1_exp/latent_xyzc_313.yaml ？

**Comment by pengsida** [comment]
这个配置文件：https://github.com/zju3dv/neuralbody/blob/master/configs/zju_mocap_exp/latent_xyzc_313.yaml
