### ISSUE TITLE
Question about volume shape (out_sh)

### ISSUE THREAD

**Issue by SuwoongHeo** [zju3dv/neuralbody#107]
Hi, 

I have a simple question about the part below. In line 116, the volume shape `out_sh` is modified so that it can be divided by 32. Is there any reason for this?

https://github.com/zju3dv/neuralbody/blob/333026fc12f33d5e732008e7094b442a0095a1e2/lib/datasets/light_stage/multi_view_dataset.py#L114-L116

Thanks :)

**Comment by pengsida** [comment]
Because the network will downsample the voxel eight times.
