### ISSUE TITLE
problem with docker install command

### ISSUE THREAD

**Issue by luoshuiyue** [zju3dv/neuralbody#108]
How can I tackele this problem when I use docker install command?
<img width="911" alt="image" src="https://user-images.githubusercontent.com/25098355/194757537-a50a07ea-e951-4ce1-9c0b-85f6ccb0c41d.png">

**Comment by pengsida** [comment]
Revise this line: https://github.com/zju3dv/neuralbody/blob/master/docker/Dockerfile#L7
