### ISSUE TITLE
How to handle this problem with docker run command?

### ISSUE THREAD

**Issue by luoshuiyue** [zju3dv/neuralbody#109]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/25098355/194810754-f4c3e804-5847-4b6e-b054-c33bab8c3ce6.png">

**Comment by luoshuiyue** [comment]
may be  it‘s because I dont install appropriate docker.

**Comment by pengsida** [comment]
I am not familiar with docker.
You could install the repo manually.
