### ISSUE TITLE
Data Acquisition

### ISSUE THREAD

**Issue by Yang-Kaixing** [zju3dv/neuralbody#112]
If I want to collect data similar to this project for my own experiments, is there a manual on how to do so?

**Comment by chingswy** [comment]
I will write a document for this later.

**Comment by Yang-Kaixing** [comment]
> I will write a document for this later.

thank you for your help.

**Comment by raj-gupta1** [comment]
> I will write a document for this later.

have you documented the process.

**Comment by pengsida** [comment]
https://chingswy.github.io/easymocap-public-doc/quickstart/prepare_mocap.html
