### ISSUE TITLE
如何使用自己的人物视频进行推理？

### ISSUE THREAD

**Issue by wangdabee** [zju3dv/neuralbody#113]
我看每个人物视频都有自己的pth参数文件，是不是我们想使用自己的自定义人物视频进行3d重建时，需要将视频制作成People-Snapshot数据集格式，经tools/process_snapshot.py处理后，训练生成pth参数文件，之后推理（python run.py --type visualize）呢？
有没有通用的3d重建模型参数文件，输入任意人物视频即可生成3d人物模型？

**Comment by JacCubk** [comment]
请问您实现该任务了么？

**Comment by pengsida** [comment]
> 有没有通用的3d重建模型参数文件，输入任意人物视频即可生成3d人物模型？

这个代码不支持你描述的功能。
