### ISSUE TITLE
About calculating the grid coordinate

### ISSUE THREAD

**Issue by chaneyddtt** [zju3dv/neuralbody#116]
Hi @pengsida ,
Thanks for your great work. I am a bit confused about the computation of the grid coordinate as shown below.  The first step convert xyz to dhw, while the last step convert it back again. I would be great if your can explain a bit about this.
![image](https://user-images.githubusercontent.com/31334319/209328585-bd976fa4-be33-434f-be4c-72e17082887f.png)

**Comment by pengsida** [comment]
Just ignore it. The code of this function is not elegant.
