### ISSUE TITLE
The calculation of near and far 

### ISSUE THREAD

**Issue by chaneyddtt** [zju3dv/neuralbody#117]
Hi @pengsida,
Thanks for the work. I have a question about the calculation of the near and far as shown below. Could you pls illustrate about why there is a need to divide the 'norm_ray' when calculating d0 and d1?

 
![image](https://user-images.githubusercontent.com/31334319/209329860-6400fa8d-347d-4eb9-a397-53b90bfa9d4d.png)

**Comment by pengsida** [comment]
Because the distance `d0` or `d1` is multiplied with `ray_d`.

**Comment by chaneyddtt** [comment]
Thanks for your response. Can I understand in this way that the d0 or d1 here represent depth values instead of distance after divided by 'norm_ray'. If this is the case, is there any assumption such that you can calculate in this way? (e.g. 'norm_ray=1' for ray aligned with the optical aixis)
