### ISSUE TITLE
Relationship between density and sdf

### ISSUE THREAD

**Issue by ryancll** [zju3dv/neuralbody#12]
Hi Sida @pengsida ,

Thank you for sharing the great work!

I'm confused about the strategy you used to extract mesh. According to your paper and code, you feed volume density to Marching Cubes algorithm, while we used to feed SDF values. Could you please explain the phyicial theories for replacing sdf with density in your work and how do you determine the threshold of the iso-surface? 

Thank you so much!

Ryan

**Comment by pengsida** [comment]
Neural radiance fields use density for volume rendering.
We manually determine the threshold of the iso-surface.
