### ISSUE TITLE
problems when training "xyzc_313"

### ISSUE THREAD

**Issue by Lcococi** [zju3dv/neuralbody#121]
RuntimeError: Error(s) in loading state_dict for Network:
	size mismatch for xyzc_net.conv0.0.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	size mismatch for xyzc_net.conv0.3.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	size mismatch for xyzc_net.down0.0.weight: copying a param with shape torch.Size([3, 3, 3, 16, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 16]).
	size mismatch for xyzc_net.conv1.0.weight: copying a param with shape torch.Size([3, 3, 3, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).

**Comment by pengsida** [comment]
https://github.com/traveller59/spconv/issues/428
