### ISSUE TITLE
Displaying outputs as per paper/repo [ISSUE]

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#124]
Hello @pengsida,
Thanks for the work. I had some errors as per spconv 2.x but I solved it somehow and was able to get the outputs.

### The results in the output_dir are images or ply only. I am unable to get the gif output as the paper or repo.
![Screenshot (673)](https://user-images.githubusercontent.com/85514219/219864181-cdefa08a-454b-4127-8100-a00d3b561148.png)
![Screenshot (675)](https://user-images.githubusercontent.com/85514219/219864183-30759823-1ce7-4ede-9bc8-354557e6ddae.png)

### OR is there a way to generate the GIF output as shown in the paper/Repo
WHAT DO YOU SUGGEST?!

**Comment by pengsida** [comment]
This code only outputs images or ply files. Please use imageio or ffmpeg to generate videos.

**Comment by Dipankar1997161** [comment]
> This code only outputs images or ply files. Please use imageio or ffmpeg to generate videos.

Thank you for the suggestion.
