### ISSUE TITLE
Perspective Change for Images

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#125]
Hello @pengsida ,

I was wondering if it is possible to generate the views of the input images from a different virtual camera location, such as top view.

### Basically what I mean is, can the visualization be done from a different camera perspective on the fly?

OR 

### do you need to create new images from a top-view camera and then do the synthesis?

I hope i was able to clarify it to you.

**Comment by pengsida** [comment]
Yes, you can create such novel views. However, the code does not provide a tool to adjust the viewpoint. You need to manually adjust the camera pose.

**Comment by pengsida** [comment]
change the input `RT` of this function: https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/multi_view_demo_dataset.py#L151

**Comment by Dipankar1997161** [comment]
Thank you for this.

In case I wish to generate **the top-view** for the Zju-mocap subjects at render, using the same function, 
I must change **"ray_o"** and **"ray_d"** which means changing the origin and direction of the image_ray, is this correct?

For any such views, the camera_origin and view-direction are important, which are initially defined in this function:  https://github.com/zju3dv/neuralbody/blob/120737bb9bf37d6c605d75b1278a6bd7a4bc0810/lib/utils/if_nerf/if_nerf_data_utils.py#L8

However, I am unable to understand where these R and T values coming from? are they fixed in any config files used for render or Do I have to manually create a file to maintain a proper camera position?

What do you think could be the possibility here??

This is my first ever encounter with NERF-based modeling, so I have such doubts.

**Comment by pengsida** [comment]
Please read the code, and you will know how to set `RT`: https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/multi_view_demo_dataset.py

**Comment by Dipankar1997161** [comment]
So after the code thoroughly, here is what I understood.

The Class Dataset initializes all the values. So K and RT are actually loaded with this line:
### K, RT = render_utils.load_cam(ann_file) 

then checking the function, I found it loads the **"annots.npy"** from the respective subject dataset eg: Coreview_387
This numpy file is generated by get_**annots.py** which uses the **"intri.yml and extri.yml" files**,

So based on the camera number, If i manually change the **"Rot_camera_B and T_camera_B"**, in the YML FILES, I will be changing the camera pose.
![Screenshot 2023-02-25 143139](https://user-images.githubusercontent.com/85514219/221359640-c7a1b7de-d803-41ba-844b-4eefdde3272f.png)

I guess I am correct here??   

Please let me know. Thank you

**Comment by pengsida** [comment]
Yes, you are right.
You could change the way to load the camera poses.

**Comment by Dipankar1997161** [comment]
Ok, but one doubt I have, 
If I update the yml files, it will change the camera pose.

Do I need to generate different metadata from Smpl? Like the canonical.pkl and camera.pkl files? 
Or just changing the Yml files and generating new annots.py will be enough to render new views?

**Comment by pengsida** [comment]
1. I recommend you to design a way to revise the `RT` instead of changing the content of yml files. You can revise the code.
2. No, you do not need to re-train the models.
