### ISSUE TITLE
Human 3.6 data for NeuralBody

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#126]
Hello @pengsida,

I saw that you have given the configs for the h36m dataset. I was wondering, do you have the metadata from the smpl, mask, and images for the h36m dataset? 

It would be great if you have even for a single h36m subject. Seeing that I can do for the rest of the subjects.

Also, have you trained NeuralBody on Human3.6 dataset?

Do let me know. Thank you.

**Comment by pengsida** [comment]
The license of Human3.6M dataset does not allow us to distribute its data. https://github.com/zju3dv/animatable_nerf/blob/master/INSTALL.md#human36m-dataset
