### ISSUE TITLE
Vertices and Params for custom dataset

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#127]
Hello @pengsida,

You closed the last issue since you said you cannot share the smpl paramaters or camera poses for h36m. Which I totally understand.

1. Could you tell me the way to get the camera parameters for h36m?  Since it is not my dataset, I cannot manually calibrate the intri and extr camera params with a chessboard and then use easy-mocap to receive the yml files (I checked a Chessboard demo on youtube for easymocap)

2. Will I get those for the vertices and params which are the smpl parameters by simply running the demo.md of easymocap?  I don't think so. If possible, could you please link the section or the doc file on EasyMocap from where I can generate the vertices and Params.  
3. Do I need to train h36m on Easymocap to get the smpl params? Because I did not find a training script there.?

I am really sorry for asking these many questions. I have organized the whole dataset just the major ones are missing.

Thank you in advance.

**Comment by pengsida** [comment]
1. It provides the camera parameters.
2. Yes.
3. No.

**Comment by Dipankar1997161** [comment]
Ok, it is clear now. I made the Yml files for the camera parameters of h36m, however, what is the Rotation matrix ( 3 X 1) 
That is I am not understanding. 
I added the R(3x3) T(3x1) in extr and then the K and distortion matrix too. 

But what about the 3x1 R matrix. ? Could you clarify that?

**Comment by pengsida** [comment]
The original T matrix.
