### ISSUE TITLE
Capableof generating .obj file or not

### ISSUE THREAD

**Issue by Marianoeli** [zju3dv/neuralbody#128]
I wanna ask that is this model capable of generating .obj file fully textured as output or not

**Comment by pengsida** [comment]
The model only generates untextured ply files. https://github.com/zju3dv/neuralbody#visualization-on-zju-mocap

<img width="832" alt="image" src="https://user-images.githubusercontent.com/11582122/222874624-797b3163-bd18-441c-9d25-f569b3de0a3b.png">
