### ISSUE TITLE
foreground segmentation for neural body

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#129]
@pengsida  HEY,

I have seen for the zju-mocap dataset, you have a folder called **"mask_cihp"** which is basically a foreground segmentation, probably used the original images and the black mask backgrround.

Could you recommend which module or tool can I possibly use to achieve this, since there are tons out there???

Thanks

**Comment by chingswy** [comment]
Check [here](https://chingswy.github.io/easymocap-public-doc/install/install_segment.html)

**Comment by Dipankar1997161** [comment]
@chingswy 
Thanks for the response. I am doing that currently.  
I got another question which was not answered in EasyMocap repo too.. 

For EasyMocap we need openpose to get the SMPL parameters.. but my system is Linux and as per OpenPose repo.. it fails to work well.

Is there any alternative that I can use in this scenario?

**Comment by chingswy** [comment]
We provide the `yolo+hrnet` mode, this can be used with simple PyTorch.
