### ISSUE TITLE
Organizing custom data

### ISSUE THREAD

**Issue by Pbb-land** [zju3dv/neuralbody#13]
Hi Sida @pengsida ,

Thank you for sharing the great work!

I'm trying to run neural body on my custom monocular video. I've already run video avatars, only get "reconstructed_poses.hdf5","consensus.obj" and "consensus.pkl". What should I do to export the SMPL parameters and SMPL vertices to two directories params and vertices?

Thank you so much!

**Comment by pengsida** [comment]
I will upload the code that processes People-Snapshot dataset.

**Comment by Pbb-land** [comment]
Thank you very much~!

**Comment by pengsida** [comment]
https://github.com/zju3dv/neuralbody#process-people-snapshot

**Comment by treesturn** [comment]
@Pbb-land Hi how did u obtain the reconstructed_poses.hdf5 file?
