### ISSUE TITLE
How to test the model on my own monocular video ?

### ISSUE THREAD

**Issue by MarkZuruck** [zju3dv/neuralbody#131]

**Comment by MarkZuruck** [comment]
Im trying to test the method on my own video where I am turning in front of the camera in order to construct a 3D model of my body, but I am not finding any way!

**Comment by MarkZuruck** [comment]
@pengsida @chingswy

**Comment by pengsida** [comment]
Similar way like this: https://github.com/zju3dv/neuralbody#run-the-code-on-the-custom-dataset
