### ISSUE TITLE
Skeleton Plotting After reconstruction

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#133]
Hello @pengsida 

From the last time, I have made advancements in my work, i have generated the top-view 3d reconstruction model for the zju-mocap dataset. 

One additional thing that I want to do is, Keypoint/skeleton plotting, on the black screen or even on images of the model.

The params folder for a suject, consists of the array with : Rh, Th, Poses (24x3),  Shapes(10,)
The vertices folder consists of an array with size (6890,3), thats the j_regressor i believe.

what other parameters would I require to plot the skeleton or atleast the 3d keypoints in the 3d space. If you could explain in a short way.

I would need the 3d joints - which I guess is the "poses" or are these the rotation o each joint. 
If that's the case, where are the joint locations for coreview-877 subject??

It would be really helpful.

**Comment by pengsida** [comment]
https://github.com/zju3dv/animatable_nerf/blob/master/tools/render_skeleton.py
