### ISSUE TITLE
如何 合适 的通过script处理json文件获取自建数据集的params和vertices？

### ISSUE THREAD

**Issue by 13136983989** [zju3dv/neuralbody#137]
我们在自己制作类似zju_mocap的数据集，我们使用单目视频作为输入。跟着[教程](https://github.com/zju3dv/neuralbody/tree/master/tools/custom)使用了Easymocap输入 `python3 apps/demo/mocap.py ${data} --work internet` 获取了很多json文件。我们可以通过上诉代码获取到的output-smpl-3d文件夹里的json文件通过您提供的[script](https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py)去获取适合neural body训练的数据集的params和vertices吗？

因为我们一直无法正确运行参考文档里的 [Demo for NeuralBody](https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html#demo-for-neuralbody)的代码来获取output-keypoints3d。

> > ![image](https://github.com/zju3dv/neuralbody/assets/42019021/cf995d10-f25f-41c7-a032-9bda36ac4b78)
> > 这个是用Easymocap用`python3 apps/demo/mocap.py ${data} --work internet` 得到的output-smpl-3d文件夹下的文件。我们注意到json文件里同样有`"id"，"shapes"，"poses"，"Rh"，"Th"`这些参数。

十分期待并感谢您一如既往的回复。

**Comment by pengsida** [comment]
我最近整理一个处理EasyMoCap数据的脚本。

**Comment by 13136983989** [comment]
> 我最近整理一个处理EasyMoCap数据的脚本。

因为处理这件事情可能比较急，我们可以用`output-smpl-3d/smplfull/`或`output-smpl-3d/smpl/`文件夹下的.json文件改写[script](https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py)得到数据集可用的params和vertices吗 ？ 因为不太清楚EasyMocap输出的`output-smpl-3d和output-keypoints3d`有什么区别。

**Comment by pengsida** [comment]
可以的。我们脚本是这么处理的。

**Comment by pengsida** [comment]
我更新了脚本：https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py
