### ISSUE TITLE
用EasyMoCap获得的output-smpl-3d/smpl/和output-smpl-3d/smplfull/文件夹下的json有什么不同呢？自建数据集该用哪个？

### ISSUE THREAD

**Issue by 13136983989** [zju3dv/neuralbody#138]
![image](https://github.com/zju3dv/neuralbody/assets/42019021/2941d769-8661-4cc4-9bda-a823826795f7)
左边的是`output-smpl-3d/smpl/`文件夹下的.json文件 右边的是`output-smpl-3d/smplfull/`文件夹下的.json文件。 请问我该用哪个文件夹下的.json文件[提取](https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py)出params和vertices呢？我们注意到只有`"poses"`有所不同

**Comment by pengsida** [comment]
https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py#L88 脚本里写了，用output-smpl-3d。

**Comment by 13136983989** [comment]
十分感谢热情且细致的回复！

**Comment by pengsida** [comment]
"output-smpl-3d/smplfull/"是原始的smpl参数，"output-smpl-3d/smpl/"是EasyMoCap定义的smpl参数。

**Comment by ellzeycunha0** [comment]
> 十分感谢热情且细致的回复！

请问在easycomap里怎么生成output-smpl-3d/smpl？
