### ISSUE TITLE
自制zju_mocap数据集，如何获取animatable_nerf中'lbs'文件夹下的所有所需要的.npy文件呢?

### ISSUE THREAD

**Issue by 13136983989** [zju3dv/neuralbody#139]
![image](https://github.com/zju3dv/neuralbody/assets/42019021/5569130a-3e54-4efb-989e-7a36af21e260)
我们的目标是自建一个可以在[animatable_nerf](https://github.com/zju3dv/animatable_nerf)上使用的类似ZJU_MoCap的数据，我们注意到animatable_nerf需要数据集中\lbs\文件夹下包含图片所示的这些文件。这些文件该怎么获取？lbs\bweights文件夹下的.npy文件呢？

我们前两天在animatable_nerf下问了同样的[问题](https://github.com/zju3dv/animatable_nerf/issues/58)，期待并感谢您的解答。

**Comment by pengsida** [comment]
animatable nerf现在的代码可以不需要lbs\bweights文件夹下的.npy文件了。

**Comment by pengsida** [comment]
请查看这个config文件中的代码文件：https://github.com/zju3dv/animatable_nerf/blob/master/configs/aligned_nerf_pdf/aligned_aninerf_pdf_s9p.yaml

**Comment by GloryyrolG** [comment]
> animatable nerf现在的代码可以不需要lbs\bweights文件夹下的.npy文件了。

May I ask how you generate `bweights` since some work still use it? Thx & Rgds,
