### ISSUE TITLE
videoavatars vs EasyMoCap for preparing a monocular video dataset

### ISSUE THREAD

**Issue by tleyden** [zju3dv/neuralbody#140]
According to the docs:

> For a monocular video, you could estimate SMPL parameters using https://github.com/thmoa/videoavatars. The output reconstructed_poses.hdf5 file can be processed following [the instruction](https://github.com/zju3dv/neuralbody#process-people-snapshot).

But I noticed in https://github.com/zju3dv/neuralbody/issues/26#issuecomment-863849679 @chingswy mentioned that EasyMoCap will support monocular data.

Would EasyMoCap work or is videoavatars still the recommended approach?

**Comment by pengsida** [comment]
If EasyMoCap support the monocular data, we would recommend to use EasyMoCap.

**Comment by tleyden** [comment]
It seems like they do based on their readme:

> 🎉 EasyMocap v0.2 is released! We support motion capture from Internet videos. Please check the [Quick Start](https://chingswy.github.io/easymocap-public-doc/quickstart/quickstart.html) for more details.
