### ISSUE TITLE
easymocap_to_neuralbody.py脚本是否有 生成的数据 和 animatable_nerf程序 需要的维度对应不上的问题呢？

### ISSUE THREAD

**Issue by 13136983989** [zju3dv/neuralbody#141]
搞了好久 一直有类似的大大小小的错误
![image](https://github.com/zju3dv/neuralbody/assets/42019021/d56254e6-72ff-4973-a5ac-46569be4c395)

1.假如您方便的话，可以帮忙生成下params/vertices，annots.npy以及 animatable_nerf 所[需要](https://github.com/zju3dv/animatable_nerf/tree/master/tools/custom_dataset)的lbs文件下的数据文件吗？ 我们的[数据集](https://1drv.ms/u/s!Ai4XNxbYPcLikj-qbdSFGgC3sWKD?e=ydYNni)很小的，这样就不会有其余的以及下面的问题了，万分感谢。

2. [easymocap_to_neuralbody脚本](https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py)代码是否有问题 因为生成的params和vertices在最后animatable_nerf跑不起来 提示是维度错误(获取lbs/weight.npy也是同样的问题) 

3. [easymocap_to_neuralbody脚本](https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py)里没有params保存的代码。我们自己修改了 生成了params文件，但参考zju_mocap数据集的params里没有{ id: }关键值，但参考[example.json](https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/example.json)有{ id: }关键值。

4. 我们想在animatable_nerf使用自建数据集，生成lbs/weight.npy和lbs下的其余数据文件也因为params和vertices的问题没有成功。

**Comment by 13136983989** [comment]
累计问了好多问题了 我都不好意思了。如果可以帮忙直接生成下animatable_nerf可用的数据集，真的万分感激！

**Comment by pengsida** [comment]
你好，easymocap_to_neuralbody的脚本应该没问题。我没有写过animatable_nerf数据生成的脚本，所以不确定相应的问题。请自己解决。
