### ISSUE TITLE
Mask generation like Zju-mocap dataset

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#142]
Hey @pengsida,

I would like to know, how were the "Mask_cihp" and "mask" generated for the respective images in zju-mocap dataset. 

I have to create such masks for my custom dataset. Any specific model or software used in case of zju-mocap??

I have the 2d and 3d keypoints with me for my dataset, just require the masks.

I will wait for the response.

**Comment by leviome** [comment]
@Dipankar1997161 Hey bro, have you settled it down?

**Comment by treesturn** [comment]
@Dipankar1997161 Hi can i ask how did u obtain the 2d and 3d keypoints for ur own dataset?

**Comment by Dipankar1997161** [comment]
> @Dipankar1997161 Hi can i ask how did u obtain the 2d and 3d keypoints for ur own dataset?

Hello there,
So, for getting 2d joints you can either manually annotate it using CVAT or LabelMe tool.  
Another way is to use pose-estimator (Openpose, yolo-HrNet) (you can find them in Easymocap GitHub which is linked here.)

Once you get the 2d joints, you can run the Mocap.py or the mv1p.py(multi_view) files under Easymocap GitHub and you will get the smpl as well as the 3d joints. Else you can use any 2d-3d pose_lift methods available.

**Comment by treesturn** [comment]
@Dipankar1997161 thanks for the suggestions, will try them out :)
