### ISSUE TITLE
easymocap_to_neuralbody.py cannot generate params?

### ISSUE THREAD

**Issue by leviome** [zju3dv/neuralbody#146]
Hi @pengsida,
I tried `easymocap_to_neuralbody.py` to make custom dataset, but I only got `vertices`.
Is it a bug or just a personal misoperation?

**Comment by pengsida** [comment]
Yes, it is a bug. Please revise the code by yourself.

**Comment by pengsida** [comment]
I have updated the script: https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py

**Comment by xianrui-luo** [comment]
> I have updated the script: https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py

In line 63-70, I use ZJU-Mocap and get the poses of the shape [1,69], but in neuralbody I need [1,72], I wonder do I need to transform the poses?
`params = {'poses': poses, 'Rh': Rh, 'Th': Th, 'shapes': shapes}
    # np.save('params_0.npy', params)
    np.save(osp.join(param_out, "{}.npy".format(root)), params)`
