### ISSUE TITLE
easymocap to neuralbody missing cfg_model.yml

### ISSUE THREAD

**Issue by bubuton** [zju3dv/neuralbody#148]
Hi, I was following the instruction in https://github.com/zju3dv/neuralbody/tree/master/tools/custom which suggest to use the easymocap then runs the easymocap_to_neuralbody.py to get parameters in standard. I was using the triangulate (https://chingswy.github.io/easymocap-public-doc/develop/02_fitsmpl.html) method to get parameters first, but then realise that easymocap_to_neuralbody.py requires a cfg_model.yml. This is not included in the output result in easymocap, which only contains cfg_data and cfg_exp. Am I using the wrong script for easymocap? Thank you.

**Comment by CHDTevior** [comment]
Hello, and how did you solve this problem? I meet it too.

**Comment by bubuton** [comment]
Using the mocap.py will generate cfg_model.yml.

CHDTevior ***@***.***> 于2023年7月27日周四 08:17写道：
