### ISSUE TITLE
A question when train my own datasets

### ISSUE THREAD

**Issue by gushengbo** [zju3dv/neuralbody#149]
Hello, I get the camera params from ROMP, I want to know whether the cams['T'] from extri should multiplied by 1000?

def get_cams():
    intri = cv2.FileStorage('intri.yml', cv2.FILE_STORAGE_READ)
    extri = cv2.FileStorage('extri.yml', cv2.FILE_STORAGE_READ)
    cams = {'K': [], 'D': [], 'R': [], 'T': []}
    for i in range(23):
        cams['K'].append(intri.getNode('K_Camera_B{}'.format(i + 1)).mat())
        cams['D'].append(
            intri.getNode('dist_Camera_B{}'.format(i + 1)).mat().T)
        cams['R'].append(extri.getNode('Rot_Camera_B{}'.format(i + 1)).mat())
        cams['T'].append(extri.getNode('T_Camera_B{}'.format(i + 1)).mat() * 1000)
    return cams

**Comment by pengsida** [comment]
You could check the unit of `T`.

**Comment by pengsida** [comment]
If the unit is `m`, you need to multiply it by 1000.
