### ISSUE TITLE
The speficied versions in requirements.txt

### ISSUE THREAD

**Issue by wanzysky** [zju3dv/neuralbody#15]
Hi, is the code compatible with a newer version of python and corresponding dependencies?

The requirements.txt specifies the version of each library, while some of them are no longer valid for Python 3.8, e.g., open3d starts from 0.10.0.0 for Python 3.8. The reason I try a newer version of Python is I am building a Dockerfile for this project, which is based on the latest build of the docker of PyTorch.

**Comment by pengsida** [comment]
You could try it.

**Comment by pengsida** [comment]
I did not test different python versions.

**Comment by wanzysky** [comment]
Do you freeze the version of dependencies for reason or just to be cautious?

**Comment by pengsida** [comment]
Just be cautious.
