### ISSUE TITLE
Some questions about training with DDP

### ISSUE THREAD

**Issue by gushengbo** [zju3dv/neuralbody#150]
Train each epoch in the same amount of time with DDP and single graphics card.

And I find that len (data_loader) is the same. Because each batch_sampler is resampled to 500.

This means that training one epoch with two graphics cards is equivalent to training two epochs with one graphics card. Is that right?

![image](https://github.com/zju3dv/neuralbody/assets/122679046/2683e4f5-e8a3-4f5d-b6b1-9c0d82fa7435)

**Comment by pengsida** [comment]
No. For DDP, the amount of training data is 500 * number of graphics cards.

**Comment by gushengbo** [comment]
> No. For DDP, the amount of training data is 500 * number of graphics cards.



> 

Yes, that's what I mean, training 400 epochs on a single GPU in source code is equivalent to training 100 epochs on the DDP of four graphics cards. The len(data_loader) represents the training data for each GPU.

**Comment by pengsida** [comment]
Yes.

**Comment by gushengbo** [comment]
> Yes.

Thank you!
