### ISSUE TITLE
some questions about wild dataset

### ISSUE THREAD

**Issue by gushengbo** [zju3dv/neuralbody#151]
Hello, I train with my own dataset. The smpl was evaluated by Easy-mocap. The result of multi-view rendering is not normal.
![image](https://github.com/zju3dv/neuralbody/assets/122679046/db83ac08-d04a-4518-b144-7fdaff0283fa)
![image](https://github.com/zju3dv/neuralbody/assets/122679046/7589e117-25e7-4dbe-adbc-35adf8b31309)
![image](https://github.com/zju3dv/neuralbody/assets/122679046/8e35a282-5b2c-458f-9709-3c82b0eb5632)
![image](https://github.com/zju3dv/neuralbody/assets/122679046/dcae77bb-6ff6-4185-b54e-f5363d36a86f)
 
I was very confused as to whether there was something wrong with the data I had produced.

**Comment by pengsida** [comment]
It seems that the masks are not accurate.
Maybe the cameras parameters are also not accurate enough.

**Comment by gushengbo** [comment]
> It seems that the masks are not accurate. Maybe the cameras parameters are also not accurate enough.

OK，thank you! I have a question if you could ask if you've used simulation software like blender to make datasets?
