### ISSUE TITLE
A question about generating smpl parameters

### ISSUE THREAD

**Issue by ellzeycunha0** [zju3dv/neuralbody#156]
I do not know how to generate a properly formatted smpl parameters for custom datasets in EasyMocap.
Is it the command of :
"python3 apps/demo/mv1p.py ${data} --out ${data}/output/smpl --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl"
?

**Comment by Dipankar1997161** [comment]
the sub_vis are the sub folders for which u want the parameters,  so make sure to write that correctly based on your camera numbering. Zju-mocap has 20+ cameras and the numbers 1 7 13 19 are the camera numbers

**Comment by pengsida** [comment]
> I do not know how to generate a properly formatted smpl parameters for custom datasets in EasyMocap. Is it the command of : "python3 apps/demo/mv1p.py ${data} --out ${data}/output/smpl --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl" ?

Yes.
