### ISSUE TITLE
Visualise Keypoints or Skeletons

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#157]
hello @pengsida,

So I did the conversion of smpl to coco. NOW!!

In neural-body,  we did not plot the skeleton nor the key points as it is usually not part of the reconstruction. However, I want to visualise the skeleton on the images or separately. 

I came across this vis_utils file here. Can I directly use it to plot the skeletons or even just the key points on the images. 
https://github.com/zju3dv/neuralbody/blob/301ab711418dd118b59eed833e34aa4d39e1cc0b/lib/utils/vis_utils.py

or Is there anything, I must take care in this regards, do let me know. 

2. The 3d points to be used for plotting will be smpl_poses or smpl_joints? and do we need the vertices and j_regressor too or just the 3d joints are enough.

thank you

**Comment by pengsida** [comment]
Sorry. I do not remember how to use this function. Please try it by yourself.
Or you could open an issue on the repo of EasyMoCap. Qing Shuai is more familiar with these visualization things than me.

**Comment by Dipankar1997161** [comment]
@pengsida, 
I was able to plot the skeletons in both 3d and 2d using the above functions.

I have a question regarding zju-mocap dataset, so if you can clarify.
There are 24 smpl joints present in the dataset, which do not have the eyes and nose coordinates.

1. So is it possible in any way to regress them? like maybe using smpl_45 joints to extract the eyes and nose coordinates?
2. Or maybe can we interpolate to find the nose joint(The most important one for me) in your dataset? -- I am kinda not sure, how can I interpolate this...

Reason - I want to convert them into coco, but when I converted, the nose joints are missing.
Kindly let me know, if there's a way. 

Here are the results so far
![258787912-234b4d6e-2a84-46c4-a5d2-f15562a49748](https://github.com/zju3dv/neuralbody/assets/85514219/d0e6d32a-ade4-4350-b6db-805c0796ce8f) ![258787918-c3a091fc-95b3-4a2c-82e9-a42adce5483b](https://github.com/zju3dv/neuralbody/assets/85514219/9088e674-5144-4534-9137-c47a352c7353)

**Comment by Dipankar1997161** [comment]
I interpolated the nose joints. Thanks, I can close this section now
