### ISSUE TITLE
Installation for windows

### ISSUE THREAD

**Issue by jhng83** [zju3dv/neuralbody#158]
Hi,

I am a Windows user, i got stuck at this line following the install.md
export CUDA_HOME="/usr/local/cuda-10.0", instead of running this line, I added my cuda to path instead with the enviroment name as CUDA_HOME. 
However, when I was running "python setup.py bdist_wheel", I got "no CUDA toolset found" error.
I also tried dding the path to my cuda in the cmake file directly using the set() function, but stll problem persist. 

I was wondering if you have any workaroun for this issue?

**Comment by pengsida** [comment]
Sorry. I am not familiar with the Windows system.
