### ISSUE TITLE
Training Custom dataset like people_snapshot example

### ISSUE THREAD

**Issue by treesturn** [zju3dv/neuralbody#159]
Hello I am trying to use this model on a custom dataset, given a mp4 file how do you generate the masks.hdf5, keypoints.hdf5 and camera.pkl. From what I understand these 3 files are needed to process the dataset and train the model?

![image](https://github.com/zju3dv/neuralbody/assets/77474648/392376ef-547e-4a31-ab7e-b1a4034c31b0)

**Comment by treesturn** [comment]
how to generate masks images and keypoints

**Comment by Dipankar1997161** [comment]
> @pengsida how to generate masks images and keypoints

are you working on a mono view or a multi_view,  you can always use EasyMocap for all such file generations

**Comment by treesturn** [comment]
@Dipankar1997161 thanks for the reply! i have managed to obtain the masks and keypoints hdf5 files, now im trying to obtain the reconstructed_poses.hdf5 file, do u by any chance know how to get that file?

**Comment by pengsida** [comment]
You could use this for generating masks: https://github.com/zju3dv/im4d/blob/main/docs/studio_data_preprocess.md#mask
