### ISSUE TITLE
Visualising unseen poses or frames

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#162]
@pengsida, 

So I was able to train h36m on neuralbody but I trained 1 action per subject and rendered the necessary images. 
Lets say: 
action - Greeting
subject - S8

now If I have to render the other actions of the SAME subject S8, do I need to train the model again OR can I just pass the new set of smpl parameters for the new action - Posing and just render them? 
Considering the camera values would be the same, but new poses rotation due to action.

What are your thoughts on this? Does something like this possible??

**Comment by pengsida** [comment]
Revising the dataset can satisfy your need.
