### ISSUE TITLE
question about mask_cihp

### ISSUE THREAD

**Issue by Fkmog** [zju3dv/neuralbody#163]
I use the code from Self-correction for human parsing and get the mask-schp、mask-schp-instance and mask-schp-parsing, I choose mask-schp as mask_cihp in my custom work. However I find that the pictures of mask_cihp from CorwView313 are all grey ,not really colorful . Should I change my custom mask_cihp pictures into grey?

**Comment by pengsida** [comment]
No. The segmentation results look gray in the format of image.
