### ISSUE TITLE
zju_mocap dataset’s name with id

### ISSUE THREAD

**Issue by KID-1412-git** [zju3dv/neuralbody#164]
I would like to know the name corresponding to each dataset ID. For example, the 313 is Twirl, but others?

**Comment by pengsida** [comment]
https://drive.google.com/file/d/1I5BQ0b9P4hVpgWnQvLQnTSHulVcIxasi/view?usp=sharing

**Comment by KID-1412-git** [comment]
Thank you for your reply！
