### ISSUE TITLE
camera coordinate system

### ISSUE THREAD

**Issue by zhaojiancheng007** [zju3dv/neuralbody#165]
Thanks for your contribution!
I've got a question when dealing with zju_mocap dataset. I'm wondering on what **coordinate system** the camera parameter (**D, K, E load from annots.npy**) is on?

**Comment by KID-1412-git** [comment]
Hi, have you solved this problem yet? I'm also want to know it.

**Comment by arnabdeypolimi** [comment]
I have a similar problem. any solution?

**Comment by pengsida** [comment]
> Thanks for your contribution! I've got a question when dealing with zju_mocap dataset. I'm wondering on what **coordinate system** the camera parameter (**D, K, E load from annots.npy**) is on?

D means distortion coefficients. The camera parameters are used to transform world-space points to camera-space points.
