### ISSUE TITLE
create obj, ply files for mesh

### ISSUE THREAD

**Issue by Dipankar1997161** [zju3dv/neuralbody#166]
hey @pengsida, hope you doing well.

I have a basic query.  Could you tell me how can I create the obj or ply files for meshes??  I do not know if its possible from easymocap directly.

I actually need the mesh files to convert the generated SMPL to SMPLx.. I have the joints, poses, betas of each subject.  
I think i need the vertices??  

I look forward to hear from you

**Comment by Dipankar1997161** [comment]
> Hi @Dipankar1997161, I am familiar with this function of EasyMoCap. Please ask @chingswy.

😅 wait you are familiar??

**Comment by pengsida** [comment]
Sorry, it is a typo.
