### ISSUE TITLE
Mocap dataset vertex to image 2D

### ISSUE THREAD

**Issue by xcharxlie** [zju3dv/neuralbody#167]
hi there,

I wonder how to convert your vertices to 2D image coordinates. The SMPL vertex is supposed to be in a specific space, though it seems like you have converted the coordinates already? But even so I couldn't accurately project it to 2D perfectly. May I ask how you did that. Thank you

**Comment by chingswy** [comment]
How do you project it given camera parameters?

**Comment by xcharxlie** [comment]
Alright, I think I got it. Thank you
