### ISSUE TITLE
The md5 value of datasets

### ISSUE THREAD

**Issue by wanzysky** [zju3dv/neuralbody#17]
Hi, I have recently downloaded datasets from the given links. The zip files seem broken that I can't open them. Can you please provide the md5 sum of the files?

**Comment by pengsida** [comment]
I have deleted the zip files.

**Comment by pengsida** [comment]
Are all the zip files are broken?

**Comment by wanzysky** [comment]
No, I just failed to download zju_mocap, even though I have tried many times.

Onedrive will pack it as a zip file when downloading the fold, but finally, it can't be opened since file explore regarded it as broken.

**Comment by pengsida** [comment]
You could download the zip files one by one, while not downloading the whole fold.

**Comment by robot0321** [comment]
![image](https://user-images.githubusercontent.com/11347296/114984268-8497f400-9ecc-11eb-8f4a-ed6a5a7e7ac6.png)

I have the same issue. Is it fine to download from the dataset homepage?
here: https://graphics.tu-bs.de/people-snapshot

The data in that homepage only contains 220MB and your data seems over 4GB. What is the difference?

**Comment by pengsida** [comment]
I have processed the People-Snapshot dataset.
You could download the zip files one by one.
