### ISSUE TITLE
Could you please update the link to renderings of ZJU-MoCAP

### ISSUE THREAD

**Issue by ChenYutongTHU** [zju3dv/neuralbody#171]
https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/Ea3VOUy204VAiVJ-V-OGd9YBxdhbtfpS-U6icD_rDq0mUQ?e=cAcylK

Hi authors, 

Could you help update the link to the rendering results of ZJU-MoCap which expires? 

* `05/13/2021` To make the following works easier compare with our model, we save our rendering results of ZJU-MoCap at [here](https://zjueducn-my.sharepoint.com/:u:/g/personal/pengsida_zju_edu_cn/Ea3VOUy204VAiVJ-V-OGd9YBxdhbtfpS-U6icD_rDq0mUQ?e=cAcylK) and write a [document](supplementary_material.md) that describes the training and test protocols.
 
Great thanks!

Best,
Yutong

**Comment by pengsida** [comment]
https://drive.google.com/drive/folders/1hoViTAnfUjBJFn09y-x3A4a9q7NXerkt?usp=sharing
