### ISSUE TITLE
The faces id in PLY files is not same with smpl faces?

### ISSUE THREAD

**Issue by wzmsltw** [zju3dv/neuralbody#18]
Hi sida

When I tried to read modify the smpl verts in people_snapshot/female3c/smpl/0.ply, I find the faces of ply is not same with faces of obj files. Do you know why and how to solve?

ply = trimesh.load("0.ply")
faces = ply.faces

which is not equal to the faces in smpl_neural.pkl

**Comment by wzmsltw** [comment]
And what is the relation between verts in vertices/0.npy and smpl/0.ply ? It also seems different

**Comment by pengsida** [comment]
Do not use trimesh. It may revise the mesh vertices and faces.
`vertices/0.npy` is the vertices of `smpl/0.ply`.

**Comment by wzmsltw** [comment]
Thanks!
