### ISSUE TITLE
Render SMPL mesh fits w.r.t capture cameras

### ISSUE THREAD

**Issue by sergeyprokudin** [zju3dv/neuralbody#20]
Hi,

First of all, thanks a lot for the great work and for releasing the code!

I was wondering if you can share\navigate me to the code that will make SMPL visualisations like the ones you provide here:

https://zju3dv.github.io/zju_mocap/

Basically, I would like to render the SMPL mesh fits with the same camera parameters as the original RGB video capture. I assume this is easily achievable with the provided visualisation code in the [run.py](https://github.com/zju3dv/neuralbody/blob/master/run.py), but got a bit lost in the details, so I'd appreciate a little guidance :) 

Thanks a lot in advance!

~Sergey

**Comment by pengsida** [comment]
https://github.com/zju3dv/EasyMocap/blob/master/doc/quickstart.md

`python3 apps/demo/mv1p.py ${data} --out ${out} --vis_det --vis_repro --undis --sub_vis 1 7 13 19 --vis_smpl`

https://github.com/zju3dv/EasyMocap/blob/master/apps/demo/mv1p.py#L80

**Comment by sergeyprokudin** [comment]
great, thanks a lot for the prompt response!
