### ISSUE TITLE
bug in snapshot demo codes and preprocessing

### ISSUE THREAD

**Issue by hongsukchoi** [zju3dv/neuralbody#21]
Hi, thanks for your great work.

I followed the installation and data pre-processing guideline, and obtained mesh vertices in **.npy** files.
However, the demo code dataloaders (i.e. snapshot_demo.py, snapshot_perform.py, snapshot_mesh.py) use **.ply** files, which do not exist. Where do I get these .ply files? 

```Python
    def prepare_input(self, i):
        # read xyz, normal, color from the ply file
        ply_path = os.path.join(self.data_root, 'smpl', '{}.ply'.format(i))
        xyz, nxyz = if_nerf_dutils.get_smpl_data(ply_path)
```

**Comment by pengsida** [comment]
Hi, I have fixed the bug.
Please git pull the latest code.

**Comment by hongsukchoi** [comment]
Thanks:)
