### ISSUE TITLE
Some masks were lost in **mask_cihp** directory in 315 dataset.

### ISSUE THREAD

**Issue by forevertsyj** [zju3dv/neuralbody#22]
Hi, thanks for your great work!

The released ZJU 315 dataset has 2185 images in total with corresponding parameters and images. However, it seems some masks were lost in **mask_cihp** directory, which only has 1622 items. Could you please release the missing masks of mask_cihp?

Thank you!

**Comment by pengsida** [comment]
I will update this recently.

**Comment by pengsida** [comment]
I have updated the 315 sequence.

**Comment by forevertsyj** [comment]
Thanks!
