### ISSUE TITLE
freeglut(foo): failed to open display 'localhost:11.0'

### ISSUE THREAD

**Issue by twowwj** [zju3dv/neuralbody#23]
Hi Sida,

When I ran the code 
"# visualize a specific mesh
python tools/render_mesh.py --exp_name female3c --dataset people_snapshot --mesh_ind 226 "

The shell reported the info : freeglut(foo): failed to open display 'localhost: 11.0'

I don't think this is a big error, but may be something wrong with it.
Have you met this problem ever before?

thanks!

**Comment by pengsida** [comment]
This visualization code requires the computer to have a display.

**Comment by twowwj** [comment]
Thanks for your reply.
So I need a computer with a screen to show it.
The shell terminal doesn't work for this.
