### ISSUE TITLE
something about data

### ISSUE THREAD

**Issue by hao-zhao-1997** [zju3dv/neuralbody#24]
This is some mistakes with mask in mask_cihp of coreview_387 from 360 to 370 frame, could you chek it ?
like this:
![17_gt](https://user-images.githubusercontent.com/32841739/120062283-ecc52280-c093-11eb-97f3-c45da76477c3.png)
![19_gt](https://user-images.githubusercontent.com/32841739/120062285-ef277c80-c093-11eb-8821-994ec080e91d.png)

or could you provide the background img of every camera? Because I think the BackgroundMattingV2 will give a more better segmentation.   : )

**Comment by pengsida** [comment]
These masks are generated using https://github.com/Engineering-Course/CIHP_PGN
I do not have the background image.

**Comment by hao-zhao-1997** [comment]
ok, thanks for your reply.
