### ISSUE TITLE
Question about the comparison on ZJU-MoCap between Neural volume and neuralbody

### ISSUE THREAD

**Issue by Xianjin111** [zju3dv/neuralbody#25]
Thank you for your perfect work.

I want to try Neural Volume on ZJU-MoCap. Could you please tell me how to generate the pose.txt on your ZJU-MoCap dataset by using KRT? 

Thank you very much.

**Comment by pengsida** [comment]
I am not faimiliar with the data format of Neural Volumes.
You could first learn about the format of pose.txt.

**Comment by Xianjin111** [comment]
> I am not faimiliar with the data format of Neural Volumes.
> You could first learn about the format of pose.txt.

Thank you for your suggestion.
