### ISSUE TITLE
How to proceed with training with custom monocular data?

### ISSUE THREAD

**Issue by Heloworkdl** [zju3dv/neuralbody#26]
I'm trying to trainning with a custom monocular video dataset. 
but the provided file seems to be the training data for a multi-view camera.
How to proceed with training with custom monocular data?

**Comment by chingswy** [comment]
I will update the training code for custom monocular data at [EasyMocap](https://github.com/zju3dv/EasyMocap) soon. Please stay tuned!

**Comment by pengsida** [comment]
I have updated the document of training on the custom dataset, which adds a configuration about the training on monocular videos: https://github.com/zju3dv/neuralbody/tree/master/tools/custom
