### ISSUE TITLE
training on Human3.6M

### ISSUE THREAD

**Issue by hongsukchoi** [zju3dv/neuralbody#27]
Hi,

do you have any plan to release the training code on Human3.6M?
I tried myself, but the outputs have minor artifacts which are not found in your results.
![89](https://user-images.githubusercontent.com/31090011/122718191-99677e00-d2a7-11eb-9e4e-bb24206b6347.jpg)

Do you have any idea for the reason?
I used the official mask data from Human3.6M dataset for training.

**Comment by pengsida** [comment]
I can sort out the code, but I cannot release the dataset.
The quality of original masks of Human 3.6M is not very good.

**Comment by hongsukchoi** [comment]
Thanks for your prompt response.
Do you mean you can look into my code?
And did you use other source of masks for training the model on Human3.6M? If so, what is it?

**Comment by pengsida** [comment]
I mean that I can sort out the training code of Human 3.6M in this repository.
I manually fix the masks of Human3.6M.

**Comment by hongsukchoi** [comment]
Great!
So do you think the artifact is due to bad masks??
This is the full result using modified demo codes.

https://user-images.githubusercontent.com/31090011/122721784-05e47c00-d2ac-11eb-9686-04c9573c7d22.mp4

**Comment by pengsida** [comment]
Yes.

**Comment by pengsida** [comment]
I have sorted out the configuration file about training on the Human3.6M dataset: https://github.com/zju3dv/neuralbody/blob/master/configs/h36m_exp/latent_xyzc_s9p.yaml
