### ISSUE TITLE
Can't visualization with vis_snapshot.py

### ISSUE THREAD

**Issue by bruinxiong** [zju3dv/neuralbody#28]
Thanks to this fabulous work. However, when l use vis_snapshot.py to visualize smpl parameters of People-Snapshot, I get the following error:
/app/tools$ python vis_snapshot.py 
INFO - 2021-06-22 15:08:19,340 - acceleratesupport - OpenGL_accelerate module loaded
INFO - 2021-06-22 15:08:19,345 - arraydatatype - Using accelerated ArrayDatatype
Traceback (most recent call last):
  File "vis_snapshot.py", line 84, in <module>
    renderer = Renderer(height=1080, width=1080, faces=faces)
  File "/app/tools/snapshot_smpl/renderer.py", line 23, in __init__
    self.renderer = pyrender.OffscreenRenderer(height, width)
  File "/home/linxiong/miniconda/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/linxiong/miniconda/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/linxiong/miniconda/lib/python3.8/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "/home/linxiong/miniconda/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 171, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/linxiong/miniconda/lib/python3.8/site-packages/pyglet/window/__init__.py", line 575, in __init__
    display = pyglet.canvas.get_display()
  File "/home/linxiong/miniconda/lib/python3.8/site-packages/pyglet/canvas/__init__.py", line 95, in get_display
    return Display()
  File "/home/linxiong/miniconda/lib/python3.8/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

How to solve it ? I find some solutions via google, but all don't work.
Thanks!

**Comment by bruinxiong** [comment]
I run this code in docker container.

**Comment by pengsida** [comment]
This visualization code requires the computer to have a display.

**Comment by bruinxiong** [comment]
@pengsida Thank you for your reply. Of course, I connect a display. I have solved the visulization issues caused by PyOpenGL, pyglet and freeglut3. By the way, I found that if I use Dockerfile to build docker image, after run the container, maybe the unknown device type error from spconv library will be reported. This issue may relate to the version of spconv, CUDA, Pytorch and even python. So, if some guys meet this issue like me. Please refer those links ( https://github.com/traveller59/spconv/issues/58, https://github.com/traveller59/spconv/issues/152) to solve. In other words, change to lower version of spconv, such as v.1.0 not v.1.2.1 in spconv.sh and modify the Dockerfile to build the available image with corresponding version of cuda, cudnn and pytorch.

**Comment by bruinxiong** [comment]
Furthermore, if some guys meet the error like me for vis_snapshot.py and render_mesh.py as following:
libGL error: No matching fbConfigs or visuals found libGL error: failed to load driver: swrast
you may refer to this link (https://github.com/jessfraz/dockerfiles/issues/253), maybe it will help you to solve the issue.

**Comment by pengsida** [comment]
Thank you!

**Comment by zshyang** [comment]
> @pengsida Thank you for your reply. Of course, I connect a display. I have solved the visulization issues caused by PyOpenGL, pyglet and freeglut3. By the way, I found that if I use Dockerfile to build docker image, after run the container, maybe the unknown device type error from spconv library will be reported. This issue may relate to the version of spconv, CUDA, Pytorch and even python. So, if some guys meet this issue like me. Please refer those links ( [traveller59/spconv#58](https://github.com/traveller59/spconv/issues/58), [traveller59/spconv#152](https://github.com/traveller59/spconv/issues/152)) to solve. In other words, change to lower version of spconv, such as v.1.0 not v.1.2.1 in spconv.sh and modify the Dockerfile to build the available image with corresponding version of cuda, cudnn and pytorch.

Hi @bruinxiong , how do you solve the no display issue?
