### ISSUE TITLE
Novel poses?

### ISSUE THREAD

**Issue by Depersonalizc** [zju3dv/neuralbody#29]
If I understand it correctly, the way you reconstruct some reference footage is by estimating SMPL parameters and posing the model. So my question is: 

_Given a trained model, is it possible to arbitrarily pose the model by manually adjusting the SMPL parameters (those outside the training data)?_ 

I guess in principle it should somewhat work. Sadly I'm having some trouble finding the exact places for tweaking those parameters. Could you kindly help me out by providing some guidance? Many thanks!

**Comment by pengsida** [comment]
Yes.
You could generate new SMPL models by revising the SMPL parameters here: https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/extract_vertices.py#L9
