### ISSUE TITLE
About the SparseConvNet

### ISSUE THREAD

**Issue by 07hyx06** [zju3dv/neuralbody#3]
Hi! 
I wonder how to represent the deformed mesh with structured latent code, i.e. the input of SparseConvNet.
Can you release the supplementary material?

**Comment by pengsida** [comment]
You will find it easy when you see the code.

**Comment by 07hyx06** [comment]
Some other questions.
1. Why there are two columns, i.e. ours and ours*, in the frame 1 setting in Table 1&2?
2. Are the results of neuralbody in Figure 5 is reconstructed from the multi-view video?

**Comment by pengsida** [comment]
1. The our* means the model trained only on the first frame. The our means the model trained on all video frames.
2. Yes.

**Comment by 07hyx06** [comment]
I still can not figure out the difference between these two columns..
![FastStoneEditor1](https://user-images.githubusercontent.com/52267384/105016207-534e8a00-5a7d-11eb-86f3-1c4d0250292b.jpg)

**Comment by 07hyx06** [comment]
So the OURS column in Frame1 means training on all frames and test on the 1st frame?

**Comment by pengsida** [comment]
Yes.
