### ISSUE TITLE
Training batch size

### ISSUE THREAD

**Issue by dlehgo14** [zju3dv/neuralbody#30]
Thanks for your great work and implementations. 
I am trying to train neuralbody with a custom monocular video whose size is 480*480. 
The batch size in all yaml configuration files you offered is set to 1, but training with 1 batch size took so little GPU memory (about 0.3 Gb).
So, I modified "N_rand" to somewhat bigger one (1024 -> 24576), because increasing batch size occurs some CUDA error.
Is it reasonable way?
In the paper, it said training with 4 2080 ti took about 14 hours. 
How did you set the batch size and N_rand in your experiments?

**Comment by pengsida** [comment]
I set the batch size to 1 and N_rand to 1024.
It is reasonable to make `N_rand` bigger.
