### ISSUE TITLE
unexpected things about training custom monocular video 

### ISSUE THREAD

**Issue by hzhao1997** [zju3dv/neuralbody#32]
I want to process my video using neuralbody and the poses are estimated by octopus. But I got abnormal results as follows. Could you give me some advice? : )
[0.zip](https://github.com/zju3dv/neuralbody/files/6758276/0.zip)

**Comment by pengsida** [comment]
Which yaml file did you use?

**Comment by pengsida** [comment]
And which command?

**Comment by hzhao1997** [comment]
I run the command `python train_net.py --cfg_file configs/vrc_Body2D_2006_342.yaml exp_name Body2D_2006_342 resume False` with 
[vrc_Body2D_2006_342.txt](https://github.com/zju3dv/neuralbody/files/6758363/vrc_Body2D_2006_342.txt) (The *.yaml can't be uploaded and so I change its type.)

The yaml is written according to my data and snapshot_f3c.yaml.

And the train_dataset_module file is here:
[vrc.txt](https://github.com/zju3dv/neuralbody/files/6758370/vrc.txt)

**Comment by pengsida** [comment]
Please use the latest code.

**Comment by hzhao1997** [comment]
OK, I will try it and thanks for you reply.
