### ISSUE TITLE
SMPL parameters on custom dataset

### ISSUE THREAD

**Issue by Xianjin111** [zju3dv/neuralbody#33]
I have obtain the json format of SMPL parameters on our dataset by using EasyMocap. I would like to ask is there any tool could be used to convert the json format to .npy format?

THX

**Comment by pengsida** [comment]
I will write a script to process the SMPL parameters from EasyMocap latter.

**Comment by Xianjin111** [comment]
> I will write a script to process the SMPL parameters from EasyMocap latter.

Thank you so much!

**Comment by pengsida** [comment]
I have updated the code: https://github.com/zju3dv/neuralbody/blob/master/zju_smpl/easymocap_to_neuralbody.py
The command is `python zju_smpl/easymocap_to_neuralbody.py`.
