### ISSUE TITLE
transform smpl from the world coordinate to the smpl coordinate

### ISSUE THREAD

**Issue by ljq2020** [zju3dv/neuralbody#34]
Hi,

Thanks for the great work! I have a question about how to get the `params['Rh']` and `params['Th']` used in `multi_view_dataset.py` , and it would be nice if you can give me a pointer for it. When I use my own dataset, I want to transform smpl from the world coordinate to the smpl coordinate, but I do not have the R and T.

**Comment by pengsida** [comment]
https://github.com/zju3dv/EasyMocap/blob/master/doc/02_output.md#attention-for-smplsmpl-x-users
