### ISSUE TITLE
No such file or directory: 'data/people_snapshot/female-3-casual/params.npy'

### ISSUE THREAD

**Issue by gav1n-cheung** [zju3dv/neuralbody#36]
Excuse me, sir. Maybe a stupid problem. I wanna to visualize the single women. But  when I run the run.py, I find the dataset file has no filename as .npy. So the .npy is the dataset provided or I have to do something to git it ?
There is what I get from terminal
`~/Desktop/Program/PCLDeepLearning/neuralbody(master*) » python run.py --type visualize --cfg_file configs/snapshot_exp/snapshot_f3c.yaml exp_name female3c vis_novel_view True num_render_views 144
load model: data/trained_model/if_nerf/female3c/latest.pth
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 91, in run_visualize
    data_loader = make_data_loader(cfg, is_train=False)
  File "/home/cheung/Desktop/Program/PCLDeepLearning/neuralbody/lib/datasets/make_dataset.py", line 84, in make_data_loader
    dataset = make_dataset(cfg, dataset_name, transforms, is_train)
  File "/home/cheung/Desktop/Program/PCLDeepLearning/neuralbody/lib/datasets/make_dataset.py", line 27, in make_dataset
    dataset = _dataset_factory(is_train)
  File "/home/cheung/Desktop/Program/PCLDeepLearning/neuralbody/lib/datasets/make_dataset.py", line 22, in _dataset_factory
    dataset = imp.load_source(module, path).Dataset(**args)
  File "lib/datasets/light_stage/monocular_demo_dataset.py", line 29, in __init__
    self.params = np.load(params_path, allow_pickle=True).item()
  File "/home/cheung/anaconda3/envs/neuralbody/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/people_snapshot/female-3-casual/params.npy'
`

**Comment by pengsida** [comment]
Did you set up the dataset: https://github.com/zju3dv/neuralbody/blob/master/INSTALL.md#people-snapshot-dataset

**Comment by gav1n-cheung** [comment]
When I use process_snapshot.py, I get another error:
`~/Desktop/Program/PCLDeepLearning/neuralbody/tools(master*) » python process_snapshot.py
Traceback (most recent call last):
  File "process_snapshot.py", line 104, in <module>
    camera = read_pickle(camera_path)
  File "process_snapshot.py", line 13, in read_pickle
    with open(pkl_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/people_snapshot/female-3-casual/camera.pkl'`

I just copy the dataset to the data file, and not create soft link.

**Comment by gav1n-cheung** [comment]
And I run your dataset(zju_mocap), there are two error.
`UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
`
and 
`ValueError: /home/cheung/spconv/src/spconv/spconv_ops.cc 87
unknown device type
`
My enviorment is CUDA 11.1 and pytorch 1.8.1. RTX 30X GPU could not install earlier version CUDA and pytorch, is it the reason for these error?

Sorry,sir. Maybe my question is not universal. Thanks so much.

**Comment by pengsida** [comment]
1. You need to download the smpl model from the official website.
2. You could set the number of workers smaller.
