### ISSUE TITLE
question about sample_ray_h36m function

### ISSUE THREAD

**Issue by starhiking** [zju3dv/neuralbody#39]
https://github.com/zju3dv/neuralbody/blob/ca1af9ad4dd50010cc7354cbe814f84a6baf1199/lib/utils/if_nerf/if_nerf_data_utils.py#L198

1.这里的msk不是二值图，用msk!=0 会不会更好点？

https://github.com/zju3dv/neuralbody/blob/ca1af9ad4dd50010cc7354cbe814f84a6baf1199/lib/utils/if_nerf/if_nerf_data_utils.py#L178

2. 为什么要将边缘元素置0？后续操作完全采样不到

https://github.com/zju3dv/neuralbody/blob/ca1af9ad4dd50010cc7354cbe814f84a6baf1199/lib/utils/if_nerf/if_nerf_data_utils.py#L202

3. 训浙大313数据集时，msk去畸变之后才有01以外的值，并不能说明13就是人脸区域的标签，为什么这里这么处理（虽然n_face是0）

**Comment by pengsida** [comment]
1. 需要用msk == 1，因为边缘处的mask设为了100, 这些区域是不被采样的。
2. 因为边缘分割不准。
3. 因为n_face是0，这部分代码其实没有用到。一开始做实验的时候有专门增加人脸部的采样频率，来让脸部更清楚。后来没有继续采用这个采样策略，因为脸部已经足够清楚。
