### ISSUE TITLE
test on monocular video?

### ISSUE THREAD

**Issue by SienChen1997** [zju3dv/neuralbody#4]
Hello @pengsida ,thanks for releasing code of this great work!The results is very impressive,i was wondering how to  test on monocluar videos like People-Snapshot dataset just as showned in paper?Could you give some instruction about this? thx!

**Comment by pengsida** [comment]
I will release the data in three weeks.

**Comment by pengsida** [comment]
I have uploaded the data and instruction.

**Comment by SienChen1997** [comment]
Thanks a lot! However the link of People-Snapshot dataset maybe isn't correct.I only found the pretrained_model.When I downloaded the dataset and run the visualization on People-Snapshot i found that there have some files generated which is not inclued in original dataset,and i wonder  is there have the modified dataset or a script  dealing with the dataset？

**Comment by pengsida** [comment]
Thanks for pointing this.
I have modified the link: https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/Eo9zn4x_xcZKmYHZNjzel7gBdWf_d4m-pISHhPWB-GZBYw?e=Hf4mz7
