### ISSUE TITLE
Reg. process_snapshot.py and frankmocap support

### ISSUE THREAD

**Issue by nitthilan** [zju3dv/neuralbody#40]
A query regarding preprocessing of people_snapshot dataset. 

I see in the implementation that the SMPL vertices are stored as the base version of the SMPL male/female model and no pose or beta params are applied to the SMPL vertices. Is this because the people snapshot dataset has all the data as A pose and SMPL default parameters are as A pose? or Am I missing the pose and beta param applied to the SMPL vertices?

Also, do you plan to add support for using the output of Frankmocap outputs?

Thanks for sharing your code. This is a very cool idea

**Comment by pengsida** [comment]
1. In People-Snapshot, the pose and beta parameters have been applied to the vertices of SMPL vertices.
2. No, we do not plan to support the output of Frankmocap. We will release the code that estimates human poses of monocular videos in https://github.com/zju3dv/EasyMocap

**Comment by nitthilan** [comment]
Can you point out where the pose and beta parameters are applied to SMPL vertices?

**Comment by pengsida** [comment]
https://github.com/zju3dv/neuralbody/blob/master/tools/process_snapshot.py#L145

**Comment by nitthilan** [comment]
I tried using this code. However, the vertices produced by this code are identical for every frame. Further, I think initially you had shared the people_snapshot dataset too instead of the actual link. In that dataset, there was an example dataset for female-3-casual which had precomputed vertices. The values produced by this script do not match the values of the precomputed vertices. I am not sure why?

**Comment by nitthilan** [comment]
Thanks for the response. I figured out the issue.
