### ISSUE TITLE
Question about the dimension of the ray_o and ray_d

### ISSUE THREAD

**Issue by Xianjin111** [zju3dv/neuralbody#41]
When I use custom dataset, the dimension of the ray_o and ray_d will become[1, 1023, 3] as the pic shown:
![企业微信截图_16285698776529](https://user-images.githubusercontent.com/46471572/128834538-b1baf75c-0ca1-4a17-ae3f-70749cf54b07.png)
![企业微信截图_16285698411682](https://user-images.githubusercontent.com/46471572/128834665-7f913262-54fc-4f5b-a263-7562d9288329.png)
![企业微信截图_16285698307534](https://user-images.githubusercontent.com/46471572/128834566-d4b5d119-4a09-4dfd-bd72-2be033a58414.png)
Could you give me some ideas to solve it?
Thx!

**Comment by pengsida** [comment]
Which dataset do you use?

**Comment by Xianjin111** [comment]
> Which dataset do you use?

I found the problem caused by the number of chunk(2048). I set the chunk smaller, the problem disappeared.

**Comment by Xianjin111** [comment]
Thank you again.
