### ISSUE TITLE
How to get model with my own video data?

### ISSUE THREAD

**Issue by Happyrealone** [zju3dv/neuralbody#42]
请问，如果我想使用自己的视频制作人物模型，应该怎么操作呢？
Excuse me, if I want to use my own video to make character models, what should I do?
要首先生成SMPL参数嘛？如果是的，那怎么样生成呢？
Do you want to generate smpl parameters first? If so, how to generate it?
我按照videoavatars要求，运行了代码，可是仍然需要camera.pkl，keypoints.hdf5，masks.hdf5，这些文件应该怎样生成呢？
I ran the code according to the requirements of videoavatars, but I still need camera.pkl, keypoints.hdf5 and masks.hdf5. How should these files be generated?
还是说，您发布的代码中有更简洁的输入方式？直接输入视频即可。
Or are there more concise input methods in the code you publish? Just input the video directly.

**Comment by pengsida** [comment]
1. 请按照videoavatars的代码生成数据，生成数据以后按照这个代码的README跑代码。
2. 没有更简洁的输入方式。
