### ISSUE TITLE
No basicModel_f_lbs_10_207_0_v1.0.0.pkl

### ISSUE THREAD

**Issue by HYRobin** [zju3dv/neuralbody#43]
Excuse Me Sir, I did'nt find   basicModel_f_lbs_10_207_0_v1.0.0.pkl   and basicmodel_m_lbs_10_207_0_v1.0.0.pkl in the project. 
 so when i  invoke python tools/process_snapshot.py to create *.npy  .  where can i  find this two files thank you very much!!

**Comment by l-mengwei** [comment]
> > I meet the same problem, how do you solve it?
> 
> I download .pkl file at https://github.com/autocyz/smpl_understand/tree/master/models , and it works

which folder did you put it? Thanks

**Comment by 3489837350** [comment]
/path/to/people_snapshot/female-3-casual I think, maybe you can read the code in process_snapshot.py, it's clear.
