### ISSUE TITLE
OpenGL errors

### ISSUE THREAD

**Issue by guoyun2020** [zju3dv/neuralbody#46]
While I was trying to run mesh visualization demo by   ``` python tools/render_mesh.py --exp_name female3c --dataset people_snapshot --mesh_ind 226  ```, I encountered with these errors which was related to OpenGL below.

b'0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'
Compilation failure for fragment shader:
b'0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'
Linker failure: 
b'error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader'

I think it could be the version of OpenGL making a difference. Can you give me your version of OpenGL and explain how to  make it? Thanks so much.

**Comment by pengsida** [comment]
```
PyOpenGL==3.1.1a1
cyglfw3==3.1.0.2
```

Pip install these libraries.
