### ISSUE TITLE
Training image size on custom data

### ISSUE THREAD

**Issue by neilgogogo** [zju3dv/neuralbody#48]
Hello, I saw in the training data, the images are 1024x1024 and 1080x1080. When comes to my custom data, the training images size is 1920x1080, rather than the square ( 1x1 ) images. I am wondering if the size has any influence on the result, do I need to resize my image to 1080x1080?

Many thanks

**Comment by pengsida** [comment]
No, there is no influence.

You need to change the `H` and `W` in the yaml file.

**Comment by neilgogogo** [comment]
thx;)
