### ISSUE TITLE
Wrong depth map?

### ISSUE THREAD

**Issue by FrozenBurning** [zju3dv/neuralbody#49]
![image](https://user-images.githubusercontent.com/35674081/132444568-363ab094-b8e1-4fd5-a77f-4f15df52378a.png)
![image](https://user-images.githubusercontent.com/35674081/132444640-f76b28a3-4504-4be8-b77b-902b7a9a4392.png)
@pengsida Great work! However, I'm concerned about the depth map generated from your model. I run visualization on Snapshot dataset by the following command:
`python run.py --type visualize --cfg_file configs/snapshot_exp/snapshot_f3c.yaml exp_name female3c vis_novel_view True num_render_views 144`
Note that I've uncommented the lines w.r.t. saving the depth map in function `visualize` and got the result shown above. 
What are the artifacts behind the person in the scene? and why there is no artifact in the rendered rgb image? Cause rgb_map comes from `torch.sum(weights[..., None]*rgb, -2)`

**Comment by pengsida** [comment]
Maybe because the artifacts have the same color as the background.

**Comment by FrozenBurning** [comment]
Thanks for your prompt response. Do you have any idea why the model learns such an artifact after training? One interesting observation is that it happens when the camera moves to novel views. By visualization result of the depth map, when the camera's motion is clockwise around the human body, the artifact appears when the camera is moving in-between the observed views (front->right->back->left ). And because it's an artifact with human body shape, I'm just wondering whether it has semantic meaning or some explainable ways of training dynamics. Just for discussion, thx!

**Comment by pengsida** [comment]
Maybe it is caused by the volumetric rendering. NeRF set the last dist as `1e10` in the volume rendering: https://github.com/zju3dv/neuralbody/blob/master/lib/networks/renderer/nerf_net_utils.py#L23

**Comment by FrozenBurning** [comment]
Thanks! Closed
