### ISSUE TITLE
Trouble with installing

### ISSUE THREAD

**Issue by Pbb-land** [zju3dv/neuralbody#5]
Hello @pengsida ,thanks for releasing code of this great work! I'm troubling with installing spconv now(python setup.py bdist_wheel). My configuration is Ubuntu 20.04+CUDA 11.1+Cudnn8.1.1+Pytorch1.8. Do I need to reinstall CUDA 10.0 even Ubuntu 18.04?

**Comment by pengsida** [comment]
I did not try the torch 1.8.
How about installing torch 1.4+cu100 and cuda 10.0?

**Comment by bennyguo** [comment]
@Pbb-land Installing with the master branch of spconv solved the problem.

**Comment by ClimberY** [comment]
> @Pbb-land Installing with the master branch of spconv solved the problem.

May I ask which version of spconv you used last?
