### ISSUE TITLE
issue with the cmu panoptic

### ISSUE THREAD

**Issue by neilgogogo** [zju3dv/neuralbody#50]
Thank you very much for your awesome work, I met a issue when playing with the cmu pano
I tried to replicate this project using the CMU panoptic data, but when I tried to visualize the result, I get such issue.

I find the upper part of the human body is missing like this: I used four views including different directions.
![image](https://user-images.githubusercontent.com/53148705/132446569-a42c0420-0971-4d90-8bc7-36cb052e1c6d.png)

**Comment by pengsida** [comment]
Try `lib.networks.renderer.if_clight_renderer` instead of `lib.networks.renderer.if_clight_renderer_mmsk`: https://github.com/zju3dv/neuralbody/blob/master/configs/zju_mocap_exp/latent_xyzc_313.yaml#L95

**Comment by neilgogogo** [comment]
Thank you very much for your reply, I modified it on the YAML without training again and the result looks better. But it is kinda weird that the upper part of the man is still missing. Could it be the season that I only use 100 frames during the training process? I will train it today again.

![image](https://user-images.githubusercontent.com/53148705/132619601-17500b3d-7bc7-4333-8b42-925860127f25.png)

**Comment by pengsida** [comment]
It seems that the 3D bounding box of this human is wrong.

**Comment by neilgogogo** [comment]
![image](https://user-images.githubusercontent.com/53148705/132834787-0b5cfae4-f2df-4306-b3f2-9155d7fafb1b.png)
Pardon me for poor understanding,
is this the 3D bounding box? Does it seem to be calculated by the max-min of the SMPL after R T pose translation?

**Comment by neilgogogo** [comment]
So the possible reason may be that smpl is not accurate?

**Comment by pengsida** [comment]
1. Yes. The bounding box is the max-min of the SMPL.
2. I am not sure. You could visualize the SMPL model and the bounding box.

**Comment by neilgogogo** [comment]
thank you very much for your patience, I finally find the reason, the smpl vertices are in smpl coordinate rather than world coordinate, after changing it, it works.

**Comment by wangguangyuan** [comment]
@neilgogogo   
I also encountered this problem. I think you said that it is a spml coordinate system problem. Can you be more specific? Thank you so much!
