### ISSUE TITLE
The scale and position of generated mesh

### ISSUE THREAD

**Issue by MarcoG5** [zju3dv/neuralbody#51]
First I would like to thank u for your great work and making it public!
About 3D Reconstruction module of your network, I noticed that the scale and position of reconstruction mesh is not correspond to the input camera parameters. Is there anyway to rescale and reposition the polygon mesh so that it can mapping to original images?
Thank You!

**Comment by pengsida** [comment]
Uncomment the two lines: https://github.com/zju3dv/neuralbody/blob/master/lib/networks/renderer/if_mesh_renderer.py#L49

**Comment by xiegongsheldon** [comment]
(NEURALBODY) xsc@xsc-Precision-3650-Tower:~/workspace/neuralbody/neuralbody$ python run.py --type visualize --cfg_file configs/snapshot_exp/snapshot_f3c.yaml exp_name female3c vis_mesh True train.num_workers 0
load model: data/trained_model/if_nerf/female3c/latest.pth
lib/networks/renderer/if_mesh_renderer.py
the results are saved at data/result/if_nerf/female3c/mesh
  0%|                                                                                                      | 0/230 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 99, in run_visualize
    output = renderer.render(batch)
  File "lib/networks/renderer/if_mesh_renderer.py", line 50, in render
    vertices = vertices + batch['wbounds'][0, 0].detach().cpu().numpy()
KeyError: 'wbounds'
