### ISSUE TITLE
deepsnake可视化问题

### ISSUE THREAD

**Issue by MelGibson123** [zju3dv/neuralbody#53]
作者您好，我看deepsnake可视化部分时，我运行命令python run.py --type demo --cfg_file configs/sbd_snake.yaml demo_path demo_images/2009_000871.jpg ct_score 0.3
正常情况下应当输出图片结果。
但我运行命令时只load模型就结束了。没有输出结果。您能告诉我可视化怎样才能执行成功吗
![微信图片_20210918154139](https://user-images.githubusercontent.com/46376839/133880817-4633ac64-f011-46dc-a636-5ad90aff7879.jpg)

**Comment by pengsida** [comment]
这个命令只在有显示器上的电脑上能显示图片。
