### ISSUE TITLE
问题：if_clight_renderer.py缺少一个函数

### ISSUE THREAD

**Issue by Auggst** [zju3dv/neuralbody#54]
你好，首先感谢您开源您的代码。

我在跑代码的时候发现，您开源的代码在if_clight_renderer.py 这个文件中第102行的函数调用中，找不到这个prepare_sp_input()函数。

地址：[https://github.com/zju3dv/neuralbody/blob/master/lib/networks/renderer/if_clight_renderer.py](url)

**Comment by pengsida** [comment]
函数位置：https://github.com/zju3dv/neuralbody/blob/master/lib/networks/renderer/if_clight_renderer.py#L29

**Comment by Auggst** [comment]
感谢回答，可能之前被我误删了。
