### ISSUE TITLE
About reproduce the result of paper

### ISSUE THREAD

**Issue by twowwj** [zju3dv/neuralbody#55]
Hi Sida,

This work is wonderful. I have successfully deployed the required environment.
But the problem is when I reproduce the result of paper using this code:
python run.py --type evaluate --cfg_file configs/zju_mocap_exp/latent_xyzc_313.yaml exp_name xyzc_313

I can only obtain the relatively low values.
313(Twirl): 
ssim: 0.967 (reproduced results)
psnr: 30.54 (reproduced results)
whereas the paper showed:
ssim: 0.971
psnr: 30.56

I test it on one Tesla V100 GPU.
I notice that you conducted the experiments using four 2080ti GPUs.
Does this cause by distributed training?
Looking forward to your reply!

**Comment by pengsida** [comment]
The results are very similar.
It is probably caused by the variation of training.

**Comment by daixiangzi** [comment]
> Hi Sida,
> 
> This work is wonderful. I have successfully deployed the required environment. But the problem is when I reproduce the result of paper using this code: python run.py --type evaluate --cfg_file configs/zju_mocap_exp/latent_xyzc_313.yaml exp_name xyzc_313
> 
> I can only obtain the relatively low values. 313(Twirl): ssim: 0.967 (reproduced results) psnr: 30.54 (reproduced results) whereas the paper showed: ssim: 0.971 psnr: 30.56
> 
> I test it on one Tesla V100 GPU. I notice that you conducted the experiments using four 2080ti GPUs. Does this cause by distributed training? Looking forward to your reply!
Are you testing on the pretrained model they provide?
