### ISSUE TITLE
I am confused about the folder vertices and smpl in the dataset

### ISSUE THREAD

**Issue by Miles629** [zju3dv/neuralbody#59]
This work is very attractive. I am currently studying the code and article. I would appreciate it very much if you could answer some questions .

I have learned the input data are "smpl vertices".
When loading the data, the code does not load the contents in the "smpl" folder, but load "vertices" folder and make a transfer in the file "monocular_dataset.py"
```
        # transform smpl from the world coordinate to the smpl coordinate
        Rh = self.params['pose'][i][:3]
        R = cv2.Rodrigues(Rh)[0].astype(np.float32)
        Th = self.params['trans'][i].astype(np.float32)
        xyz = np.dot(xyz - Th, R)
```
Does this mean the data in "vertices" is the "SMPL vertices in world coordinate" and the "xyz" is "SMPL vertices in smpl coordinate"?
The data in "smpl" folder is the visualization of "vertices" ?
Use method embadding to establish the mapping of 6890 vertices and 16 dimensional latent code Z, This is called "Structure latent code" in the article. I want to know if my understanding is correct.

Thanks for your reading, respect！

**Comment by pengsida** [comment]
1. The data in "vertices" is the "SMPL vertices in world coordinate", and the "xyz" is "SMPL vertices in smpl coordinate".
2. The data in "smpl" folder is the visualization of "vertices".
3. Each SMPL vertex is assigned a 16 dimensional latent code.
