### ISSUE TITLE
Unable to generate mesh

### ISSUE THREAD

**Issue by WANGEOGEO** [zju3dv/neuralbody#6]
Hi guys,

While using 377 group from ZJU-Mocap dataset, I found that all the meshes I generate are empty: though .ply files are generated successfully, there's no mesh in any file. Each file only contains an empty space.
No errors or warnings appear during the code execution:
`python run.py --type visualize --cfg_file configs/latent_xyzc_mesh_377.yaml exp_name xyzc_377`

btw the outcome of previous two tests:
`python run.py --type visualize --cfg_file configs/xyzc_demo_377.yaml exp_name xyzc_377`
and 
`python run.py --type visualize --cfg_file configs/xyzc_perform_377.yaml exp_name xyzc_377`
are successful, and the outcomes are visible.

What is the possible cause for this problem? Will it be helpful using other datasets to try again?

**Comment by pengsida** [comment]
It works in my computer.
What tools do you use to visualize the mesh?

![image](https://user-images.githubusercontent.com/11582122/112104053-a65fcd00-8be5-11eb-94f0-c9c2aeba7cbd.png)

**Comment by WANGEOGEO** [comment]
I am using xcode to show the mesh. So may I ask what is the size of your mesh file? My generated mesh files are all about 4 MB.

**Comment by pengsida** [comment]
You could visualize the mesh file using meshlab.
The size of my mesh files is also around 4 MB.

**Comment by WANGEOGEO** [comment]
Thanks a lot, problem solved. 
Lol, I never thought about using another app to visualize the mesh.
