### ISSUE TITLE
Configs of Nueral Volume

### ISSUE THREAD

**Issue by mjmjeong** [zju3dv/neuralbody#60]
Thank you for sharing your code.

However, I have few questions about neural volume

1. I can not find the code light_stage.can_smpl in neural volume config. 
```
train_dataset_module: 'lib.datasets.light_stage.can_smpl'
train_dataset_path: 'lib/datasets/light_stage/can_smpl.py'
test_dataset_module: 'lib.datasets.light_stage.can_smpl'
test_dataset_path: 'lib/datasets/light_stage/can_smpl.py'
```

2. If I change the dataset part code as followings, 
```
train_dataset_module: 'lib.datasets.light_stage.multi_view_dataset'
train_dataset_path: 'lib/datasets/light_stage/multi_view_dataset.py'
test_dataset_module: 'lib.datasets.light_stage.multi_view_dataset'
test_dataset_path: 'lib/datasets/light_stage/multi_view_dataset.py'
```
I think I can not find the difference between the 'zju_mocap_frame1_exp' setting. 

Could you explain the method to training neural volume with the first frame of videos?

**Comment by pengsida** [comment]
This code does not contain the training of neural volume.
