### ISSUE TITLE
About the test result of sequence386

### ISSUE THREAD

**Issue by Time-Lord12th** [zju3dv/neuralbody#61]
Hello:
when running the command`python run.py --type evaluate --cfg_file configs/zju_mocap_exp/latent_xyzc_386.yaml exp_name xyzc_386
` , I found the result is much worse than sequence313, and the rendering result is also worse:
![image](https://user-images.githubusercontent.com/53140195/143829386-17dd6dbb-49a2-441b-b1a2-69492c45c9d7.png)

![frame0000_view0001_gt](https://user-images.githubusercontent.com/53140195/143829623-f4c56820-77be-4525-b189-ad210b5d9d86.png)

![frame0000_view0001](https://user-images.githubusercontent.com/53140195/143829634-163701f3-9833-4c98-bd47-2652a224bf88.png)
I don't know the reason for that, could you please help me?

Thanks.

**Comment by pengsida** [comment]
The results look strange.
I did not encounter this problem in my environment.

**Comment by Time-Lord12th** [comment]
thanks for your reply, I will check my operations again.
