### ISSUE TITLE
PointCloud' object has no attribute 'faces'

### ISSUE THREAD

**Issue by yangyin2016** [zju3dv/neuralbody#62]
hello， i run the command ：python tools/render_mesh.py --exp_name female3c --dataset people_snapshot --mesh_ind 226， i got the error

Traceback (most recent call last):
  File "tools/render_mesh.py", line 132, in <module>
    faces = mesh.faces
AttributeError: 'PointCloud' object has no attribute 'faces'

I don't know the reason for that, could you please help me?

**Comment by pengsida** [comment]
Install `trimesh==3.8.15`.

**Comment by yangyin2016** [comment]
hello，the version of trimesh is 3.8.15 in my code environment，i have no idea how to solve the problem

**Comment by pengsida** [comment]
I did not encounter this problem.
