### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by yangyin2016** [zju3dv/neuralbody#63]
hello， when i run the command
python run.py --type visualize --cfg_file configs/snapshot_exp/snapshot_f3c.yaml exp_name female3c vis_novel_view True num_render_views 144

i got the error

RuntimeError: Error(s) in loading state_dict for Network:
        size mismatch for xyzc_net.conv0.0.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
        size mismatch for xyzc_net.conv0.3.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
        size mismatch for xyzc_net.down0.0.weight: copying a param with shape torch.Size([3, 3, 3, 16, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 16]).
        size mismatch for xyzc_net.conv1.0.weight: copying a param with shape torch.Size([3, 3, 3, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
        size mismatch for xyzc_net.conv1.3.weight: copying a param with shape torch.Size([3, 3, 3, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
        size mismatch for xyzc_net.down1.0.weight: copying a param with shape torch.Size([3, 3, 3, 32, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 32]).
        size mismatch for xyzc_net.conv2.0.weight: copying a param with shape torch.Size([3, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for xyzc_net.conv2.3.weight: copying a param with shape torch.Size([3, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for xyzc_net.conv2.6.weight: copying a param with shape torch.Size([3, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for xyzc_net.down2.0.weight: copying a param with shape torch.Size([3, 3, 3, 64, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 64]).

can you help me， what i should do？

**Comment by pengsida** [comment]
Very strange.
Where did you download the pre-trained model?

**Comment by yangyin2016** [comment]
I have solved the problem， because my spconv version is 2.x，i install spconv1.2，the code  run successfully！

**Comment by ClimberY** [comment]
> I have solved the problem， because my spconv version is 2.x，i install spconv1.2，the code run successfully！

I met the same problem, how did you solve it?

**Comment by lixinghe1999** [comment]
although downgrade to 1.X can solve it, regard to the performance improvement of spconv 2.X, I personally think it is more beneficial to just permute the checkpoint and load it to the spconv 2.X style code.
