### ISSUE TITLE
confused about smpl coordinate

### ISSUE THREAD

**Issue by 15211** [zju3dv/neuralbody#64]
作者您好，非常感谢您的工作。目前我正在阅读该论文和学习代码，对于其中一处存在疑问：
`        # transform smpl from the world coordinate to the smpl coordinate ` 
`         Rh = self.params['pose'][i][:3]` 
`         R = cv2.Rodrigues(Rh)[0].astype(np.float32)` 
`         Th = self.params['trans'][i].astype(np.float32)` 
`         xyz = np.dot(xyz - Th, R)` 

1.请问pose 和 trans是否是从smpl坐标系到世界坐标系的变换参数？

2.请问此处变换是否可以类比您此前的camera space -> world space变换的部分？

3.请问其中由smpl坐标系构建的空间是否可以被称为“canonical space”呢？

非常感谢您的阅读！

**Comment by pengsida** [comment]
1. 是的。
2. 和camera space到world space变换类似。
3. 我把zero pose下的smpl坐标系称为canonical space。

**Comment by 15211** [comment]
> 

非常感谢您的解答，对我帮助很大！

对于您的回答，我有些疑惑的地方，想向您再次确认下，pose和trans是用于：

smpl  坐标系 -> world 坐标系 变换的参数，还是
world 坐标系 -> smpl  坐标系 变换的参数呢？

如果是前者，我对其中.dot(xyz - Th, R)这一步操作存在疑惑：能否使用此“R”（smpl -> world变换矩阵）将其转换到原来的smpl坐标空间？

再次感谢您的耐心解答！

**Comment by pengsida** [comment]
`np.dot(xyz - Th, R)`用于将坐标从世界坐标系变换到smpl坐标系。

**Comment by 15211** [comment]
> `np.dot(xyz - Th, R)`用于将坐标从世界坐标系变换到smpl坐标系。


@pengsida 
非常非常感谢您的耐心解答。我最后总结一下我的理解，您看一看是不是正确的。

pose 和 trans是 “smpl坐标系->世界坐标系 ”的变换参数。code使用xyz = np.dot(xyz - Th, R)将xyz点从world坐标系变换到smpl坐标系。

最近紧急接触了图形学，连续问了诸多问题，抱歉打扰到您。
祝大佬科研顺利！！ : )

**Comment by 15211** [comment]
非常感谢，通过您的解答辅以可视化明白了

**Comment by snitchjinx** [comment]
@15211  请问你是怎么做的可视化呢？
我想把mesh用相机参数投影到视频上：
```
params = np.load(params_path, allow_pickle=True).item()
Rh = params['Rh']
R = cv2.Rodrigues(Rh)[0].astype(np.float32)
Th = params['Th'].astype(np.float32)
smpl.set_params(beta=params['shapes'].squeeze(), pose=params['poses'].squeeze())

P_camera = (R @ smpl.verts.T).T + T.ravel()
P_homogeneous = (K @ P_camera.T).T
P_2D = P_homogeneous[:, :2] / P_homogeneous[:, 2, np.newaxis]
```

以下是我得到的投影结果：

![Image](https://github.com/user-attachments/assets/5a60741f-15b0-4afc-877b-62715195cdd7)

我是哪一步弄错了呢？

**Comment by snitchjinx** [comment]
我从[这段代码](https://github.com/zju3dv/animatable_nerf/blob/f9b29c54b334e2d8404ede6a5badab6bc747dd22/tools/render_skeleton.py#L293)大概搞懂了这些参数，但是最终结果里还是有一些mis-alignment，请问这样的偏差是由于投影造成的，还是smpl参数的误差引起的呢？

![Image](https://github.com/user-attachments/assets/b318bbf1-029b-4a4f-806f-2bf68c336795)

**Comment by snitchjinx** [comment]
哦这个mis-alignment是因为我也undistort了一下投影后的2D坐标，把这一步去掉就align得很好了。
感谢作者开源这个repo，我学习到了很多！
