### ISSUE TITLE
关于训练过程中图像真值的获取

### ISSUE THREAD

**Issue by doctorwho479** [zju3dv/neuralbody#65]
您好！非常感谢您的工作和开源的代码，我在阅读代码的过程中遇到了一个问题：
在lib/train/trainers/if_nerf_clight.py中参与loss计算的两个对象维度为[1024 , 3]，这似乎不是二维图片的shape，请问这是什么含义？
在lib/evaluators/if_nerf.py中有获取图像真值的代码（如下），我尝试将其用在训练过程中，发现报错，原因是mask_at_box无法reshape。
![image](https://user-images.githubusercontent.com/60005749/145841908-22c8b6a6-e053-4049-8ac4-c2f76037db93.png)

通过比较，我发现is_train=True或者False时batch['mask_at_box'][0]的shape就不一样了，这似乎是加载的数据集不一样导致的，请问在is_train=True的情况下如何获得[H, W, C]形式的图像真值？
非常感谢。

**Comment by pengsida** [comment]
这是采样像素点的代码：https://github.com/zju3dv/neuralbody/blob/master/lib/datasets/light_stage/multi_view_dataset.py#L154
你可以通过修改采样策略得到[H, W, 3]形式的图像。
