### ISSUE TITLE
Why camera origin in 'get_ray' of 'if_nerf_data_utils.py' isn't T?

### ISSUE THREAD

**Issue by Yzmblog** [zju3dv/neuralbody#68]
Hi, it's a great and awesome work. And I have a question in 'if_nerf_data_utils.py', the camera origin in 'get_ray' is calculate by -np.dot(R.T, T), I think this is the World origin in camera coordinate, camera origin in World coordinate should be T ? I got confused by this, I would be a great help if you can answer this, thank!
![QQ图片20220114114234](https://user-images.githubusercontent.com/51486172/149447859-b77ded1a-9b9b-4fa6-aef0-e75848801097.jpg)

**Comment by pengsida** [comment]
`-np.dot(R.T, T)` is the camera origin in the world coordinate space.
The camera origin in the camera coordinate space is zero. Because RX + T = 0, the camera origin in the world space is X = -np.dot(R.T, T).

**Comment by Yzmblog** [comment]
> `-np.dot(R.T, T)` is the camera origin in the world coordinate space. The camera origin in the camera coordinate space is zero. Because RX + T = 0, the camera origin in the world space is X = -np.dot(R.T, T).

Got it, my understanding of T is wrong, Thanks for your quick reply very much!
btw, is that the definition of t in the data nerf use is different? I see the code in nerf is derectly use 't' as the ray origin.
![image](https://user-images.githubusercontent.com/51486172/149469103-ac604163-d344-487e-af3b-f112eaa652d8.png)

**Comment by pengsida** [comment]
Yes. NeRF uses the OpenGL definition.

**Comment by Yzmblog** [comment]
> Yes. NeRF uses the OpenGL definition. Our codes uses the OpenCV definition.

Got it, Thanks for your reply again!

**Comment by UestcJay** [comment]
> Yes. NeRF uses the OpenGL definition. Our codes uses the OpenCV definition.

Can you explain this in detail, I don't understand very well
