### ISSUE TITLE
Question of metric

### ISSUE THREAD

**Issue by jhkim0759** [zju3dv/neuralbody#69]
I wonder what is the inputs of PSNR and SSIM metric
I think it use input RGB image and projected image of 3D reconstruction 
Is that right?

**Comment by pengsida** [comment]
Yes.

**Comment by jhkim0759** [comment]
Thank you.
Is this metrics for how model can estimate 3D mesh sharply?

**Comment by pengsida** [comment]
These metrics cannot be used to estimate the quality of 3D mesh.
