### ISSUE TITLE
Rendering of PeopleSnapshot dataset does not work

### ISSUE THREAD

**Issue by xiangdonglai** [zju3dv/neuralbody#7]
Thanks for the great work!

When I try to run `python run.py --type visualize --cfg_file configs/snapshot_f3c_demo.yaml exp_name female3c`, the first error I get is that there is no this file `lib/networks/renderer/if_clight_renderer_msk.py`. I guess there may be a typo in terms of the filename `lib/networks/renderer/if_clight_renderer_mmsk.py`. Even after I rename `if_clight_renderer_mmsk.py` to `if_clight_renderer_msk.py`, it still pauses at this location https://github.com/zju3dv/neuralbody/blob/master/lib/networks/renderer/if_clight_renderer_mmsk.py#L92
I check that it happens because there is indeed no 'Ks' in the batch dict.

I tried to use `if_clight_renderer.py` in the same directory and that seems to be working, but I am not sure whether this is the right one to use. Can you help look into this? Thanks.

**Comment by pengsida** [comment]
Hi Donglai,

Happy to see your interests in my paper.
I have uploaded the file `lib/networks/renderer/if_clight_renderer_msk.py`.
To acclerate rendering, I construct visual hull during inference using the masks of training views.
`mmsk` means multi-view masks, while `msk` means single-view mask.
Since people_snapshot contains only monocular videos, I render images using `if_clight_renderer_msk`.

Best,
Sida

**Comment by Yamato-01** [comment]
Thanks for your sharing!I have used `if_clight_renderer_msk.py` you uploaded later, but I meet another problem. When I run `python run.py --type visualize --cfg_file configs/snapshot_f3c_demo.yaml exp_name female3c`, it shows "RuntimeError: Providing a bool or integral fill value without setting the optional `dtype` or `out` arguments is currently unsupported. In PyTorch 1.7, when `dtype` and `out` are not set a bool fill value will return a tensor of torch.bool dtype, and an integral fill value will return a tensor of torch.long dtype.". It reminds there maybe some problems in line 64 and line 173 of the file `if_clight_renderer_msk.py`.
Could you help solve this matter? Thanks!

**Comment by pengsida** [comment]
How about installing torch1.4.0+cu100

![image](https://user-images.githubusercontent.com/11582122/112467192-b6bca700-8da1-11eb-9891-2073888bcd90.png)

**Comment by Yamato-01** [comment]
> How about installing torch1.4.0+cu100?
> 
> ![image](https://user-images.githubusercontent.com/11582122/112467192-b6bca700-8da1-11eb-9891-2073888bcd90.png)

Thanks a lot! I have solved this problem.
