### ISSUE TITLE
SMPL parameters

### ISSUE THREAD

**Issue by caiyongqi** [zju3dv/neuralbody#72]
Hi. 
1. Only four cameras are used for training in the ZJU-Mocap dataset, but are the SMPL parameters calculated from all cameras?
2. Are the coordinates of the vertices under the vertices folder in the world coordinate system? Does the axis satisfy the right-hand rule? Because I get weird visualization results when I open the vertices file with MeshLab.
![image](https://user-images.githubusercontent.com/47025383/156930534-d9650a7d-8882-41c3-bf8b-db2c6ca08ecf.png)

**Comment by pengsida** [comment]
1. The SMPL parameters are estimated from four cameras.
2. The vertices are in the world coordinate system. I did not encounter this problem.
