### ISSUE TITLE
annots.npy

### ISSUE THREAD

**Issue by caiyongqi** [zju3dv/neuralbody#73]
Hi.
Is R in annots.npy the rotation matrix from the world coordinate system to the camera coordinate system?

**Comment by pengsida** [comment]
Yes.

**Comment by jasongzy** [comment]
I'm sorry, but according to the codes [here](https://github.com/zju3dv/neuralbody/blob/eb1c3ceedaca75c7d7b6d24c64213b4218945730/lib/utils/base_utils.py#L17) that project a 3D point in the world coordinate system to the pixel coordinate system (world-to-camera, then camera-to-pixel), R and T seem to be the **world-to-camera** parameters (extrinsic matrix).

```python
xyz = np.dot(xyz, RT[:, :3].T) + RT[:, 3:].T
```

I am confused now. Did I miss anything? @pengsida

**Comment by pengsida** [comment]
Yes, you are right.
