### ISSUE TITLE
Error when converting from Easymocap to neuralbody

### ISSUE THREAD

**Issue by bhargavbompalli** [zju3dv/neuralbody#74]
Hi,

When running the code "easymocap_to_neuralbody.py", I seem to keep getting this error:

![image](https://user-images.githubusercontent.com/83196619/157071304-fbf721d9-572d-40f9-b046-84d73479a553.png)

The SMPL model which I used was version 1.1.0. But when I replaced this with the older model (version 1.0.0), I do not get this error anymore.

However, I would like to be able to run this code on SMPL version 1.1.0, which I had originally done my recordings on. Is there any way I can make this work for version 1.1.0?

**Comment by pengsida** [comment]
You need to revise the code manually.
It is not difficult. You could debug the code.
