### ISSUE TITLE
The indicator(PSNR  SSIM) does not appear

### ISSUE THREAD

**Issue by andy-hao** [zju3dv/neuralbody#75]
![image](https://user-images.githubusercontent.com/77253450/157224002-1cf1d5d6-00cc-4002-8e55-e60cbf416e67.png)
![image](https://user-images.githubusercontent.com/77253450/157224073-e1256954-d702-482f-961e-e3e555000adf.png)
Ask for help!
After running ”python train_net.py --cfg_file configs/snapshot_exp/snapshot_f3c.yaml exp_name female3c resume False“, no metrics are generated npy. The indicator(PSNR  SSIM) does not appear. Where does the indicator result appear?

**Comment by andy-hao** [comment]
> ![图像](https://user-images.githubusercontent.com/77253450/157224002-1cf1d5d6-00cc-4002-8e55-e60cbf416e67.png) ![图像](https://user-images.githubusercontent.com/77253450/157224073-e1256954-d702-482f-961e-e3e555000adf.png)寻求帮助！运行"python train_net.py --cfg_file configs/snapshot_exp/snapshot_f3c.yaml exp_name female3c resume False"后，不会生成 npy 任何指标。指示灯 （PSNR SSIM） 不出现。指标结果显示在哪里？

Doesn't snapshot have relevant test instructions？

**Comment by andy-hao** [comment]
![image](https://user-images.githubusercontent.com/77253450/157796861-91a85328-a360-4beb-a019-d9b7583bba9a.png)
Why are the results of each evaluation different?

**Comment by pengsida** [comment]
I do not know what you want to mean.
If you know Chinese, you could ask in Chinese.
