### ISSUE TITLE
Expand the other actions(without 313,315) in the zju_mocap dataset.

### ISSUE THREAD

**Issue by Miles629** [zju3dv/neuralbody#78]
Hello, Dr. Peng. I found that only the vertices data of 313 and 315 in the ZJU dataset were comprehensive. I wonder how to expand the other actions in the dataset so that they have more vertex data to train with.
Now, the verteices data of the other actions have only 300 npy file. I would appreciate it if you could help me expand the data set of zju_mocap that I can use for training and testing.

It's really good dataset!

Thank you a lot!

**Comment by pengsida** [comment]
When did you download the ZJU-MoCap dataset?
The latest ZJU-MoCap contains all poses.
