### ISSUE TITLE
question about code 

### ISSUE THREAD

**Issue by UestcJay** [zju3dv/neuralbody#79]
many thanks for your great work! I do not understand these, can you give me some specific introduction?:
`    # obtain the bounds for coord construction

        min_xyz = np.min(xyz, axis=0)
        max_xyz = np.max(xyz, axis=0)
        min_xyz[1] -= 0.1
        max_xyz[1] += 0.1
        bounds = np.stack([min_xyz, max_xyz], axis=0)

        # construct the coordinate
        dhw = xyz[:, [2, 1, 0]]
        min_dhw = min_xyz[[2, 1, 0]]
        max_dhw = max_xyz[[2, 1, 0]]
        voxel_size = np.array(cfg.voxel_size)
        coord = np.round((dhw - min_dhw) / voxel_size).astype(np.int32)

        # construct the output shape
        out_sh = np.ceil((max_dhw - min_dhw) / voxel_size).astype(np.int32)
        x = 32
        out_sh = (out_sh | (x - 1)) + 1`

**Comment by pengsida** [comment]
The code is used to generate grid coordinates for grid_sample.
