### ISSUE TITLE
Unexpected Error when Attempting to Train Custom Dataset

### ISSUE THREAD

**Issue by bhargavbompalli** [zju3dv/neuralbody#80]
Hello,

I have been encountering this error when running the command to train the model on my custom dataset. 

My dataset is formatted exactly as shown in your README file for custom images. However, I keep receiving this error even though all my data is present and I have referred to it in the config.yaml file.

![image](https://user-images.githubusercontent.com/83196619/158919326-170db6cd-a38c-4ad0-8973-5841727c54d2.png)

![image](https://user-images.githubusercontent.com/83196619/158919375-ef9a30be-d52f-4c3d-a604-7e12b5eada6c.png)

The second image is "multi_view_custom.yaml" which I have revised to my dataset.

Can you please let me know what the error is referring to exactly and whether I need to make any changes to the .yaml file?

Thanks.

**Comment by pengsida** [comment]
Maybe the `self.ims` in your dataset is zero.

**Comment by bhargavbompalli** [comment]
Could you explain where that is? Or how to change it? Sorry I am new to this and still learning.

**Comment by bhargavbompalli** [comment]
Thanks, was able to find the issue and fix it. Although, I now receive another error:

![image](https://user-images.githubusercontent.com/83196619/159007647-5406d95e-b942-4fba-892d-bccda643dbb2.png)

**Comment by bhargavbompalli** [comment]
Fixed the above issue, was related to specifying the "training_view" in the custom.yaml file.
