### ISSUE TITLE
Unknown cause of error while training custom dataset

### ISSUE THREAD

**Issue by bhargavbompalli** [zju3dv/neuralbody#81]
Hello,

I am currently attempting to train my custom dataset and after running for a few steps, this error is returned:

![image](https://user-images.githubusercontent.com/83196619/159305407-af735c8e-2446-47bf-8d5f-6cc1604c46b2.png)

I believe the issue with my mask images. It may not be correctly the values of the mask and cannot return "coord_body" correctly.

This is an example of a mask that I am using:
![00195](https://user-images.githubusercontent.com/83196619/159305791-f3e42f75-a727-46c0-ad20-453baf4358a3.png)

Can you let me know whether this issue is related to the mask or to something else?

Thanks.

**Comment by pengsida** [comment]
Yes. It seems that the `len(coord_body)` is zero.
