### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by caiyongqi** [zju3dv/neuralbody#82]
Hi. This model doesn't seem to generate a white background.
![frame0000_view0000](https://user-images.githubusercontent.com/47025383/160519598-9ed6e899-aa41-4b9f-802f-e80597632cc4.png)

**Comment by pengsida** [comment]
What is your training command

**Comment by caiyongqi** [comment]
> What is your training command

`python -m torch.distributed.launch --nproc_per_node=2 train_net.py --cfg_file configs/zju_mocap_exp/latent_xyzc_377.yaml exp_name xyzc_377 resume False gpus "0, 1" distributed True white_bkgd True`
And I only use one frame and multi-views, i.e. `num_train_frame: 1` and `training_view: [1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,21,22]`.

**Comment by pengsida** [comment]
There may be a bug. I will look into it when I have time.
Thank you for pointing it out.

**Comment by pengsida** [comment]
I did not find this problem.
You should specify the model to render the white background during rendering novel views.
