### ISSUE TITLE
ImportError:Imageio Pillow requires Pillow, not PIL!

### ISSUE THREAD

**Issue by ClimberY** [zju3dv/neuralbody#83]
When I run "python run.py --type visualize --cfg_file configs/snapshot_exp/snapshot_f3c.yaml exp_name female3c vis_novel_view True num_render_views 144", there's an error
"ImportError:Imageio Pillow requires Pillow, not PIL!" And I have installed Pillow.

**Comment by pengsida** [comment]
Please google how to install Pillow.

**Comment by CharlieZhang1999** [comment]
Hi, I met the same problem. Did you solve it?

**Comment by potato123-hash** [comment]
Hi, I met the same problem. Did you solve it?

**Comment by qiu708** [comment]
> Hi, I met the same problem. Did you solve it?

update imageio

**Comment by wtishere** [comment]
Try `pip install --upgrade imageio`
