### ISSUE TITLE
Error when visualizing mesh with ZJU-MoCap

### ISSUE THREAD

**Issue by bhargavbompalli** [zju3dv/neuralbody#84]
Hi, I am trying to generate the mesh for the ZJU-MoCap data, but I keep receiving this error. I have already created a render images which works fine. For some reason only the meshes cannot be generated. All of the required data is in the right directories (according to the "latent_xyzc.yaml" file), yet it keeps saying there are "no tensor arguments to this function". Am I missing something?

![image](https://user-images.githubusercontent.com/83196619/161340089-81fc8695-88ed-41d4-9982-6fc9368108e9.png)

Thanks.

**Comment by pengsida** [comment]
Did you revise the code or data?

**Comment by bhargavbompalli** [comment]
No major changes to the dataset or code. Not sure what is missing.

**Comment by pengsida** [comment]
Please try the original code.
