### ISSUE TITLE
New parameters

### ISSUE THREAD

**Issue by caiyongqi** [zju3dv/neuralbody#86]
Are the parameters output by EasyMocap the old parameters _(params)_ or the new parameters _(new_params)_?

**Comment by pengsida** [comment]
Both of them are estimated by EasyMoCap. They are estimated by different versions of EasyMoCap.

**Comment by John-Yao** [comment]
@pengsida  could you provide the new setting of easymocap(such as loss setting).  I use the new param is more accurate. However, I could not get the similar accuracy of pose by newest version of EasyMocap

**Comment by pengsida** [comment]
@chingswy
