### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by 88ili88** [zju3dv/neuralbody#87]
I tried to install it on both windows and Linux thru the manual and docker installation and every single time I get an error on the same file: 
"ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/app/spconv/dist/spconv-1.2.1-cp38-cp38-linux_x86_64.whl'"
There's a screenshot of the log below, I'd really appreciate any information. 
![Screenshot from 2022-04-21 11-36-21](https://user-images.githubusercontent.com/95495428/164427169-86150b66-51ec-4fda-9a06-2613800cfd66.png)

![Screenshot from 2022-04-14 13-51-52](https://user-images.githubusercontent.com/95495428/163385147-29c2a9fb-25b9-427b-8c79-b60154270731.png)

**Comment by pengsida** [comment]
It seems that you did not correctly install spconv.
You could raise an issue in spconv repository: https://github.com/traveller59/spconv
