### ISSUE TITLE
question about /lib/utils/render_utils.py def gen_path(RT, center=None)

### ISSUE THREAD

**Issue by ssy-sheshe** [zju3dv/neuralbody#88]
While inspecting your code,I have encountered  something I cannot understand.I cannot understand the Algorithmic logic in the code，and how do the novel views generate
[https://github.com/zju3dv/neuralbody/blob/d622120b220035f5ad56a311ce2f97744b50d0a9/lib/utils/render_utils.py#L61](url)

**Comment by pengsida** [comment]
It is used to generate a spiral camera path based on the 3D spiral equation, which can be found in  https://math.stackexchange.com/questions/804702/equation-of-a-3d-spiral

Because this code is not related to the core algorithm, you can simply ignore it.
