### ISSUE TITLE
Question regarding SMPL parameters

### ISSUE THREAD

**Issue by LemonATsu** [zju3dv/neuralbody#9]
Hi,

Thanks for the great work! I have a question regarding the SMPL parameters provided in ZJU mocap dataset, and it would be nice if you can give me a pointer for it.

Currently, I'm trying to reproduce the SMPL vertices from the `shape`, `pose`, `Rh` and `Th` parameters provided in the dataset.
To do so, I use the code from [SMPLX repo](https://github.com/vchoutas/smplx) (which is also used in your code?), and feed in the provided SMPL parameters.
However, it appears that the reproduced vertices are always off by a translation (even if I applied `Rh` and `Th`).
Here is an example output for `Coreview_377/0.npy` using `SMPL_NEUTRAL.pkl` body template (the same setting as in [your code ](https://github.com/zju3dv/neuralbody/blob/master/tools/prepare_warping.py#L178)):
![Screen Shot 2021-03-26 at 1 12 17 AM](https://user-images.githubusercontent.com/10173487/112514558-6872cc80-8dd0-11eb-966f-83044813b4d1.png)
Here, the red one is the output of SMPLX repo, and blue is the data that you provided.

I traced your code [here ](https://github.com/zju3dv/neuralbody/blob/master/tools/prepare_warping.py#L178), however, it is not clear what makes the difference. 

Therefore, can you kindly provide a pointer that causes the offset?

Thanks!

**Comment by pengsida** [comment]
Hi,

I have uploaded the code and updated the document: https://github.com/zju3dv/neuralbody#potential-problems-of-provided-smpl-parameters
Please inform me If there is any problem. Thank you!

**Comment by pengsida** [comment]
I also uploaded the template model to onedrive https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/Eo9zn4x_xcZKmYHZNjzel7gBdWf_d4m-pISHhPWB-GZBYw?e=Hf4mz7

**Comment by LemonATsu** [comment]
Awesome! I will check it out and re-open the issue if I find any issues.
Thanks for the quick reply & updates!
