### ISSUE TITLE
Visualization on People-Snapshot 

### ISSUE THREAD

**Issue by muxi-0104** [zju3dv/neuralbody#92]
INFO - 2022-05-18 16:15:24,440 - utils - NumExpr defaulting to 2 threads.
load model: data/trained_model/if_nerf/female4c/latest.pth
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 88, in run_visualize
    epoch=cfg.test.epoch)
  File "/content/neuralbody/lib/utils/net_utils.py", line 381, in load_network
    net.load_state_dict(pretrained_model['net'], strict=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Network:
	size mismatch for xyzc_net.conv0.0.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	size mismatch for xyzc_net.conv0.3.weight: copying a param with shape torch.Size([3, 3, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
	size mismatch for xyzc_net.down0.0.weight: copying a param with shape torch.Size([3, 3, 3, 16, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 16]).
	size mismatch for xyzc_net.conv1.0.weight: copying a param with shape torch.Size([3, 3, 3, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
	size mismatch for xyzc_net.conv1.3.weight: copying a param with shape torch.Size([3, 3, 3, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
	size mismatch for xyzc_net.down1.0.weight: copying a param with shape torch.Size([3, 3, 3, 32, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 32]).
	size mismatch for xyzc_net.conv2.0.weight: copying a param with shape torch.Size([3, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
	size mismatch for xyzc_net.conv2.3.weight: copying a param with shape torch.Size([3, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
	size mismatch for xyzc_net.conv2.6.weight: copying a param with shape torch.Size([3, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
	size mismatch for xyzc_net.down2.0.weight: copying a param with shape torch.Size([3, 3, 3, 64, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 64]).
	size mismatch for xyzc_net.conv3.0.weight: copying a param with shape torch.Size([3, 3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
	size mismatch for xyzc_net.conv3.3.weight: copying a param with shape torch.Size([3, 3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
	size mismatch for xyzc_net.conv3.6.weight: copying a param with shape torch.Size([3, 3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
	size mismatch for xyzc_net.down3.0.weight: copying a param with shape torch.Size([3, 3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
	size mismatch for xyzc_net.conv4.0.weight: copying a param with shape torch.Size([3, 3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
	size mismatch for xyzc_net.conv4.3.weight: copying a param with shape torch.Size([3, 3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
	size mismatch for xyzc_net.conv4.6.weight: copying a param with shape torch.Size([3, 3, 3, 128, 128]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).

can you help me， what i should do？

**Comment by elahe-badali** [comment]
I've got the same problem, Any solution?

**Comment by muxi-0104** [comment]
sorry, I haven't solved the problem yet. But maybe I know the problem. If we follow the install, we will download the spconv2.x, but the project use spconv1.2. I have not find the spconv1.2 yet.

**Comment by pengsida** [comment]
> sorry, I haven't solved the problem yet. But maybe I know the problem. If we follow the install, we will download the spconv2.x, but the project use spconv1.2. I have not find the spconv1.2 yet.

Yes. Try `git checkout abf0acf30f5526ea93e687e3f424f62d9cd8313a` under the spconv directory.

**Comment by elahe-badali** [comment]
Hi @pengsida,
Thank you for your response, but the answer didn't work for me. 
I want to run this code on Colab.

![image](https://user-images.githubusercontent.com/39738835/170030418-fca09035-5156-4c7d-9ca6-0f23031421b2.png)

**Comment by pengsida** [comment]
Looks strange. I can do this on my local computer.

**Comment by muxi-0104** [comment]
> Hi @pengsida, Thank you for your response, but the answer didn't work for me. I want to run this code on Colab.
> 
> ![image](https://user-images.githubusercontent.com/39738835/170030418-fca09035-5156-4c7d-9ca6-0f23031421b2.png)

hello! have you solved the problem in Colab? I also run this code in Colab.

**Comment by elahe-badali** [comment]
> > Hi @pengsida, Thank you for your response, but the answer didn't work for me. I want to run this code on Colab.
> > ![image](https://user-images.githubusercontent.com/39738835/170030418-fca09035-5156-4c7d-9ca6-0f23031421b2.png)
> 
> hello! have you solved the problem in Colab? I also run this code in Colab.

Hello. Yes I solve it by one commit on this git. I check "git log" and that specific commit was there. Then I used these commands:
```
!git add all
!git commit -m test
```
and then I can checkout that specific commit with no error.

**Comment by elahe-badali** [comment]
But now I have another error:
![image](https://user-images.githubusercontent.com/39738835/170853576-fea92c10-1afa-42bd-9476-29e0d1debb27.png)
![image](https://user-images.githubusercontent.com/39738835/170853572-b38abe0c-c18f-4708-8a63-9b3033cb1d57.png)

any solution? @pengsida

**Comment by wtishere** [comment]
I found the solution to transform models trained in spconv 1.x into spconv 2.x format. [https://github.com/traveller59/spconv/issues/428](url)

**Comment by raj-gupta1** [comment]
@wtishere issue 428 is missing. I can't find the solution in the [link ](https://github.com/zju3dv/neuralbody/issues/url) you shared. Still getting size mismatched error.

**Comment by Dipankar1997161** [comment]
@raj-gupta1 
Where you able to solve the error for the size mismatch? 
If so could you share it with me too.

THank you in advanced

**Comment by raj-gupta1** [comment]
> @raj-gupta1 Where you able to solve the error for the size mismatch? If so could you share it with me too.
> 
> THank you in advanced

I don't remember whether the issue was resolved or not but I think changing the spconv version might have resolved the issue.   Use the modified repo for spconv which is compatible with your python version.

**Comment by Dipankar1997161** [comment]
> > @raj-gupta1 Where you able to solve the error for the size mismatch? If so could you share it with me too.
> > THank you in advanced
> 
> I don't remember whether the issue was resolved or not but I think changing the spconv version might have resolved the issue. Use the modified repo for spconv which is compatible with your python version. I hope it helps.

Thank you for the quick response. 
### I used spconv2.x due to my CUDA being 11.8 and with this code written in 1.x version, I had to change my code and basically swap the locations of the Network Weights as the new spconv (2.x) weights are placed differently And the Issue was resolved.

Thanks for your help again ^^
