### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by NBd-hub** [zju3dv/neuralbody#96]

**Comment by NBd-hub** [comment]
The command '/bin/sh -c curl -sLo cmake.tar.gz https://github.com/Kitware/CMake/releases/tag/v3.20.1/cmake-3.20.1.tar.gz  && tar -xvf cmake.tar.gz  && cd cmake-3.20.1  && ./configure  && make -j4 && sudo make install' returned a non-zero code: 56
can't finish the docker Image

**Comment by pengsida** [comment]
I do not know what causes this problem.
I am not familiar with docker.

**Comment by longxiang-ai** [comment]
> 
Hello, Pengsida, i'm going to tell you that there's a little bug in your docker. In file **spconv.sh**, after you checkout the old branch in spconv, you didn's update the submodule of spconv, which is different from the approach without docker, thus causing cmake problems for not finding missing modules pybind. And after adding this line `git submodule update --init --recursive` at the third line, the problem will be handled.

**Comment by pengsida** [comment]
I have added this line.
