### ISSUE TITLE
Question about the visualization

### ISSUE THREAD

**Issue by xjchao7** [zju3dv/neuralbody#97]
Thank you for your perfect work. I have a question about the visualization. I found that the visualization utlizes the image_rays function (https://github.com/zju3dv/neuralbody/blob/d622120b220035f5ad56a311ce2f97744b50d0a9/lib/datasets/light_stage/multi_view_demo_dataset.py#L151) different from the https://github.com/zju3dv/neuralbody/blob/d622120b220035f5ad56a311ce2f97744b50d0a9/lib/datasets/light_stage/multi_view_dataset.py#L154. I don't really understand why. Could you please explain that to me thank you.

**Comment by pengsida** [comment]
There is no difference of these two functions.

**Comment by pengsida** [comment]
sample_ray_h36m provides the ray sampling during training.
