### ISSUE TITLE
can you offer a example about zju_mocap dataset?

### ISSUE THREAD

**Issue by daixiangzi** [zju3dv/neuralbody#99]

**Comment by daixiangzi** [comment]
我使用你animatable nerf issues中提供的部分数据集 https://zjueducn-my.sharepoint.com/:f:/g/personal/pengsida_zju_edu_cn/EsCahURVXs1Gm6Oe-sF9zFABWwOLblFd_dP0Ovh8NN2d9w?e=L8P7B0，然后改了一些相关的配置文件，最后感觉20k iterations（img_loss:0.0003)就差不多收敛了，条件：单卡，CoreView_313。其中我发现你在readme中，写了这么一段：1）The newly fitted parameters locate in new_params. Currently, the released pretrained models are trained on previously fitted parameters, which locate in params。所以我的理解是不是new_params比之前的params要好，导致的这个情况。但是能否说下new_params和params的区别？

**Comment by pengsida** [comment]
new_params和params是分别用不同版本的EasyMocap得到的SMPL parameters。
